# Generated by Django 5.1.15 on 2026-09-23 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kutuphane', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetadataLookupCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn13', models.CharField(max_length=13, unique=True, verbose_name='ISBN (13 hane)')),
                ('source', models.CharField(blank=True, choices=[('MINISTRY', 'Bakanlık kataloğu'), ('OPENLIBRARY', 'Open Library')], default='', help_text='Boş: hiçbir kaynakta bulunamadı.', max_length=12, verbose_name='kaynak')),
                ('record_count', models.PositiveIntegerField(default=0, help_text='Mükerrer kayıt kuralı (§8.5): kullanıcıya kaç kayıt bulunduğu söylenir.', verbose_name='kaynaktaki kayıt sayısı')),
                ('fetched_on', models.DateField(help_text="Kaynak etiketinde gösterilir ('Bakanlık kataloğu, 23.09.2026').", verbose_name='getirilme tarihi')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='künye önerisi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
            ],
            options={
                'verbose_name': 'künye önbelleği',
                'verbose_name_plural': 'künye önbelleği',
                'ordering': ['-fetched_on', '-pk'],
            },
        ),
        migrations.AddField(
            model_name='librarypolicy',
            name='metadata_lookup_enabled',
            field=models.BooleanField(default=False, help_text='Varsayılan kapalıdır (§8.5-1). Açıkken yalnız kullanıcının başlattığı tek sorgu dışarı çıkar; dışarı yalnız ISBN gider.', verbose_name='ISBN ile künye getirme açık'),
        ),
        migrations.AddField(
            model_name='librarypolicy',
            name='metadata_lookup_ministry',
            field=models.BooleanField(default=True, help_text='Kültür ve Turizm Bakanlığı halk kütüphaneleri kataloğu (ilk sırada sorulur).', verbose_name='Bakanlık kataloğundan sorulur'),
        ),
        migrations.AddField(
            model_name='librarypolicy',
            name='metadata_lookup_openlibrary',
            field=models.BooleanField(default=True, help_text='Bakanlık kataloğunda bulunamayan numaralar için yedek kaynak.', verbose_name="Open Library'den sorulur"),
        ),
    ]
