# Generated by Django 5.1.15 on 2026-09-23 22:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kutuphane', '0002_metadatalookupcache_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarcodeReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='silinme')),
                ('year', models.PositiveSmallIntegerField(verbose_name='yıl')),
                ('first_barcode', models.CharField(max_length=10, verbose_name='ilk barkod')),
                ('last_barcode', models.CharField(max_length=10, verbose_name='son barkod')),
                ('count', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1300)], verbose_name='adet')),
                ('note', models.CharField(blank=True, default='', max_length=120, verbose_name='açıklama')),
                ('printed_at', models.DateTimeField(blank=True, null=True, verbose_name='basım onayı')),
            ],
            options={
                'verbose_name': 'boş barkod aralığı',
                'verbose_name_plural': 'boş barkod aralıkları',
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.AddField(
            model_name='copy',
            name='spine_label_printed_at',
            field=models.DateTimeField(blank=True, help_text='Boş = sırt etiketi kuyruğunda (F4). Onaylı işaret; geri alınabilir.', null=True, verbose_name='sırt etiketi basım tarihi'),
        ),
        migrations.AlterField(
            model_name='copy',
            name='label_printed_at',
            field=models.DateTimeField(blank=True, help_text='BARKOD etiketinin basım işareti. Boş = barkod etiketi kuyruğunda (F4). Onaylı işarettir (D10): PDF üretmek yazmaz, kullanıcı onaylar; geri alınabilir.', null=True, verbose_name='etiket basım tarihi'),
        ),
        migrations.AlterField(
            model_name='copy',
            name='label_verified_at',
            field=models.DateTimeField(blank=True, help_text='Yapıştırdıktan sonra barkod etiketini okutunca yazılır (F4).', null=True, verbose_name='etiket doğrulama tarihi'),
        ),
        migrations.CreateModel(
            name='LabelPrintBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='silinme')),
                ('kind', models.CharField(choices=[('SPINE', 'Sırt etiketi'), ('BARCODE', 'Barkod etiketi'), ('BOTH', 'Sırt ve barkod etiketi')], max_length=8, verbose_name='içerik')),
                ('include_qr', models.BooleanField(default=False, help_text='Varsayılan kapalı (§7.2). İçerik rakamdır, adres değil; geniş şablon ister.', verbose_name='QR kod')),
                ('order', models.CharField(choices=[('CALL_NUMBER', 'Yer numarası'), ('IMPORT_ROW', 'İçe aktarma sırası'), ('BARCODE', 'Barkod')], default='CALL_NUMBER', max_length=12, verbose_name='basım sırası')),
                ('start_cell', models.PositiveSmallIntegerField(default=1, help_text="1'den başlar, satır satır sayılır (soldan sağa, yukarıdan aşağı). Kısmen kullanılmış tabakanın ilk boş hücresi.", validators=[django.core.validators.MinValueValidator(1)], verbose_name='başlangıç hücresi')),
                ('copy_count', models.PositiveIntegerField(default=0, verbose_name='nüsha sayısı')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='basım onayı')),
                ('reverted_at', models.DateTimeField(blank=True, null=True, verbose_name='geri alma')),
                ('discarded_at', models.DateTimeField(blank=True, null=True, verbose_name='vazgeçme')),
                ('calibration', models.ForeignKey(blank=True, help_text='Boş: kaymasız (kalibrasyonsuz) basım.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='print_batches', to='kutuphane.labelcalibration', verbose_name='kalibrasyon')),
                ('reprint_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reprints', to='kutuphane.labelprintbatch', verbose_name='yeniden basılan parti')),
                ('spine_calibration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spine_print_batches', to='kutuphane.labelcalibration', verbose_name='sırt etiketi kalibrasyonu')),
                ('spine_template', models.ForeignKey(blank=True, help_text='Yalnız “sırt ve barkod etiketi” basımında, sırt etiketleri AYRI bir tabakaya basılacaksa. Boş: sırt da ana şablona basılır. İki tabaka aynı sıra ve hücre planını paylaşır (§7.2).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='spine_print_batches', to='kutuphane.labelsheettemplate', verbose_name='sırt etiketi şablonu')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='print_batches', to='kutuphane.labelsheettemplate', verbose_name='etiket şablonu')),
            ],
            options={
                'verbose_name': 'etiket basım partisi',
                'verbose_name_plural': 'etiket basım partileri',
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='LabelPrintBatchItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(verbose_name='sıra')),
                ('previous_printed_at', models.DateTimeField(blank=True, null=True, verbose_name='önceki barkod basım işareti')),
                ('previous_verified_at', models.DateTimeField(blank=True, null=True, verbose_name='önceki doğrulama işareti')),
                ('previous_spine_printed_at', models.DateTimeField(blank=True, null=True, verbose_name='önceki sırt basım işareti')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='kutuphane.labelprintbatch', verbose_name='parti')),
                ('copy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='label_batch_items', to='kutuphane.copy', verbose_name='nüsha')),
            ],
            options={
                'verbose_name': 'basım partisi kalemi',
                'verbose_name_plural': 'basım partisi kalemleri',
                'ordering': ['batch', 'position'],
            },
        ),
        migrations.CreateModel(
            name='ReservedBarcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=10, unique=True, verbose_name='barkod')),
                ('accession_no', models.PositiveBigIntegerField(unique=True, verbose_name='kayıt no')),
                ('bound_at', models.DateTimeField(blank=True, null=True, verbose_name='bağlanma')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='iptal')),
                ('cancel_reason', models.CharField(blank=True, default='', max_length=255, verbose_name='iptal gerekçesi')),
                ('copy', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reserved_barcode', to='kutuphane.copy', verbose_name='bağlandığı nüsha')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='numbers', to='kutuphane.barcodereservation', verbose_name='boş barkod aralığı')),
            ],
            options={
                'verbose_name': 'ayrılmış barkod',
                'verbose_name_plural': 'ayrılmış barkodlar',
                'ordering': ['accession_no'],
            },
        ),
        migrations.AddConstraint(
            model_name='labelprintbatch',
            constraint=models.CheckConstraint(condition=models.Q(('reverted_at__isnull', True), ('confirmed_at__isnull', False), _connector='OR'), name='ck_labelbatch_revert_needs_confirm'),
        ),
        migrations.AddConstraint(
            model_name='labelprintbatch',
            constraint=models.CheckConstraint(condition=models.Q(('confirmed_at__isnull', True), ('discarded_at__isnull', True), _connector='OR'), name='ck_labelbatch_confirm_xor_discard'),
        ),
        migrations.AddConstraint(
            model_name='labelprintbatch',
            constraint=models.CheckConstraint(condition=models.Q(('kind', 'BOTH'), models.Q(('spine_template__isnull', True), ('spine_calibration__isnull', True)), _connector='OR'), name='ck_labelbatch_spine_template_only_both'),
        ),
        migrations.AddConstraint(
            model_name='labelprintbatchitem',
            constraint=models.UniqueConstraint(fields=('batch', 'position'), name='uq_labelbatchitem_pos'),
        ),
        migrations.AddConstraint(
            model_name='labelprintbatchitem',
            constraint=models.UniqueConstraint(fields=('batch', 'copy'), name='uq_labelbatchitem_copy'),
        ),
        migrations.AddConstraint(
            model_name='reservedbarcode',
            constraint=models.CheckConstraint(condition=models.Q(('copy__isnull', True), ('cancelled_at__isnull', True), _connector='OR'), name='ck_reservedbarcode_bound_xor_cancelled'),
        ),
        migrations.AddConstraint(
            model_name='reservedbarcode',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('copy__isnull', True), ('bound_at__isnull', True)), models.Q(('copy__isnull', False), ('bound_at__isnull', False)), _connector='OR'), name='ck_reservedbarcode_bound_at'),
        ),
    ]
