# Generated by Django 5.1.15 on 2026-09-24 09:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kutuphane', '0003_etiket_kuyrugu_ve_bos_barkod'),
    ]

    operations = [
        migrations.CreateModel(
            name='KatalogAyari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='silinme')),
                ('acik', models.BooleanField(default=False, help_text='Varsayılan kapalıdır; ilk açılışta Ağ Doktoru yönlendirir (§5.2).', verbose_name='Ağ Kataloğu açık')),
                ('port', models.PositiveIntegerField(default=8765, help_text='Değişikliği güvenlik duvarı kuralını da günceller (yönetici onayı ister).', validators=[django.core.validators.MinValueValidator(1024), django.core.validators.MaxValueValidator(65535)], verbose_name='port')),
                ('dinleme_kipi', models.CharField(choices=[('ALL', 'Bütün ağ bağlantılarında'), ('SELECTED', 'Yalnız seçili IP adresinde')], default='ALL', max_length=10, verbose_name='dinleme kipi')),
                ('secili_ip', models.CharField(blank=True, default='', help_text="Yalnız 'yalnız seçili IP adresinde' kipinde kullanılır (IPv4).", max_length=15, verbose_name='seçili IP adresi')),
                ('son_afis_ip', models.CharField(blank=True, default='', help_text='Katalog afişi basıldığında yazılır; IP değişince uyarı bununla karşılaştırılır.', max_length=15, verbose_name='son afişteki IP adresi')),
                ('uyku_engelleme', models.BooleanField(default=True, help_text='Kullanıcının başlattığı uyku ve kapak kapatma engellenmez (§4.5).', verbose_name='katalog açıkken boşta kalma uykusu engellenir')),
                ('vitrin_acik', models.BooleanField(default=True, help_text='Ağ Kataloğu ana sayfasında yeni gelenler ve çok okunanlar.', verbose_name='vitrin gösterilir')),
                ('konular_acik', models.BooleanField(default=True, help_text='Ağ Kataloğunda DOS ana sınıfları ve konu dizini.', verbose_name='konu dizini gösterilir')),
                ('tahta_cidrleri', models.JSONField(blank=True, default=list, help_text="BTR'nin doğruladığı IPv4 blokları (ör. <tahta-ağı>); kural güncellemesinde kullanılır.", verbose_name='tahta ağı blokları')),
            ],
            options={
                'verbose_name': 'Ağ Kataloğu ayarı',
                'verbose_name_plural': 'Ağ Kataloğu ayarları',
                'constraints': [models.CheckConstraint(condition=models.Q(('dinleme_kipi__in', ['ALL', 'SELECTED'])), name='ck_katalogayari_dinleme_kipi'), models.CheckConstraint(condition=models.Q(('port__gte', 1024), ('port__lte', 65535)), name='ck_katalogayari_port_araligi'), models.CheckConstraint(condition=models.Q(models.Q(('dinleme_kipi', 'SELECTED'), _negated=True), models.Q(('secili_ip', ''), _negated=True), _connector='OR'), name='ck_katalogayari_secili_ip')],
            },
        ),
        migrations.CreateModel(
            name='KatalogPopuler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pencere_turu', models.CharField(choices=[('DONEM', 'Dönem'), ('AY', 'Ay')], max_length=5, verbose_name='pencere türü')),
                ('pencere', models.CharField(help_text="Dönem için '2026-2027/1', ay için '2026-09'.", max_length=20, verbose_name='pencere')),
                ('sira', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='sıra')),
                ('hesaplanma', models.DateField(verbose_name='hesaplanma tarihi')),
                ('dondu', models.BooleanField(default=False, help_text='Kapanmış pencere yeniden hesaplanmaz.', verbose_name='donduruldu')),
                ('eser', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='populer_siralari', to='kutuphane.work', verbose_name='eser')),
            ],
            options={
                'verbose_name': 'çok okunanlar sırası',
                'verbose_name_plural': 'çok okunanlar sıraları',
                'db_table': 'kd_katalog_populer',
                'ordering': ['pencere_turu', '-pencere', 'sira'],
                'constraints': [models.UniqueConstraint(fields=('pencere_turu', 'pencere', 'sira'), name='uq_katalogpopuler_sira'), models.UniqueConstraint(fields=('pencere_turu', 'pencere', 'eser'), name='uq_katalogpopuler_eser'), models.CheckConstraint(condition=models.Q(('pencere_turu__in', ['DONEM', 'AY'])), name='ck_katalogpopuler_pencere_turu')],
            },
        ),
    ]
