# Generated by Django 5.1.15 on 2026-09-24 15:39

import django.db.models.deletion
import django.utils.timezone
import shared.crypto
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kutuphane', '0004_katalog_ayari_ve_populer'),
        ('okul', '0006_kutuphane_saatleri'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssuedCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_no_index', models.CharField(max_length=64, unique=True, verbose_name='kart no kör indeksi')),
                ('issued_on', models.DateField(default=django.utils.timezone.localdate, verbose_name='veriliş tarihi')),
            ],
            options={
                'verbose_name': 'verilmiş kart numarası',
                'verbose_name_plural': 'verilmiş kart numaraları',
                'ordering': ['pk'],
                'constraints': [models.CheckConstraint(condition=models.Q(('card_no_index', ''), _negated=True), name='ck_issuedcard_index')],
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='silinme')),
                ('card_no', shared.crypto.EncryptedCharField(max_length=8, verbose_name='kart no')),
                ('card_no_index', models.CharField(editable=False, max_length=64, unique=True, verbose_name='kart no kör indeksi')),
                ('card_printed_at', models.DateTimeField(blank=True, help_text='Onaylı basım işareti; boş = kart basımı kuyruğunda. Kart yenilenince boşalır.', null=True, verbose_name='kart basım tarihi')),
                ('status', models.CharField(choices=[('ACTIVE', 'Aktif'), ('TERMINATED', 'Sonlandı')], default='ACTIVE', max_length=12, verbose_name='durum')),
                ('requested_at', models.DateField(default=django.utils.timezone.localdate, verbose_name='üyelik isteği tarihi')),
                ('started_at', models.DateField(default=django.utils.timezone.localdate, verbose_name='üyelik başlangıcı')),
                ('terminated_at', models.DateField(blank=True, null=True, verbose_name='üyeliğin sonlandığı tarih')),
                ('termination_reason', models.CharField(blank=True, choices=[('LEFT_SCHOOL', 'Okuldan ayrıldı'), ('MEMBER_REQUEST', 'Üyenin isteği'), ('RECORD_ERROR', 'Yanlış kayıt'), ('MERGED', 'Kişi kayıtları birleştirildi')], default='', max_length=16, verbose_name='sonlanma nedeni')),
                ('personnel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='library_memberships', to='okul.personnel', verbose_name='personel')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='library_memberships', to='okul.student', verbose_name='öğrenci')),
            ],
            options={
                'verbose_name': 'üyelik',
                'verbose_name_plural': 'üyelikler',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='silinme')),
                ('loaned_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='verilme zamanı')),
                ('due_date', models.DateField(db_index=True, verbose_name='iade tarihi')),
                ('returned_at', models.DateTimeField(blank=True, null=True, verbose_name='iade zamanı')),
                ('status', models.CharField(choices=[('OPEN', 'Açık'), ('RETURNED', 'İade edildi')], default='OPEN', max_length=16, verbose_name='durum')),
                ('override_reason', shared.crypto.EncryptedCharField(blank=True, default='', help_text='Yalnız gecikme engeli istisnasında; kapalı listeden (yönetici kipi).', max_length=32, verbose_name='istisna gerekçesi')),
                ('override_note', shared.crypto.EncryptedTextField(blank=True, default='', help_text='Sağlık ya da aile bilgisi yazmayın.', verbose_name='istisna açıklaması')),
                ('cardless', models.BooleanField(default=False, verbose_name='kartsız ödünç')),
                ('cardless_reason', shared.crypto.EncryptedCharField(blank=True, default='', help_text='Kapalı listeden (yönetici kipi).', max_length=32, verbose_name='kartsız ödünç gerekçesi')),
                ('copy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='kutuphane.copy', verbose_name='nüsha')),
                ('membership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loans', to='kutuphane.membership', verbose_name='üyelik')),
            ],
            options={
                'verbose_name': 'ödünç',
                'verbose_name_plural': 'ödünçler',
                'ordering': ['-loaned_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='CardRevocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_no_index', models.CharField(max_length=64, unique=True, verbose_name='kart no kör indeksi')),
                ('reason', models.CharField(choices=[('RENEWED', 'Kart yenilendi'), ('MERGED', 'Kişi kayıtları birleştirildi'), ('DELETED', 'Üyelik silindi')], default='RENEWED', max_length=10, verbose_name='iptal nedeni')),
                ('revoked_on', models.DateField(default=django.utils.timezone.localdate, verbose_name='iptal tarihi')),
                ('membership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='card_revocations', to='kutuphane.membership', verbose_name='üyelik')),
            ],
            options={
                'verbose_name': 'iptal edilmiş kart',
                'verbose_name_plural': 'iptal edilmiş kartlar',
                'ordering': ['-revoked_on', '-pk'],
            },
        ),
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['status'], name='kutuphane_membership_st_idx'),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('personnel__isnull', True), ('student__isnull', False)), models.Q(('personnel__isnull', False), ('student__isnull', True)), _connector='OR'), name='ck_membership_xor_person'),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('status', 'ACTIVE')), fields=('student',), name='uq_membership_active_student'),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('status', 'ACTIVE')), fields=('personnel',), name='uq_membership_active_personnel'),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.CheckConstraint(condition=models.Q(('card_no_index', ''), _negated=True), name='ck_membership_card_index'),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['ACTIVE', 'TERMINATED'])), name='ck_membership_status'),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'ACTIVE'), ('terminated_at__isnull', True), ('termination_reason', '')), models.Q(('status', 'TERMINATED'), ('terminated_at__isnull', False), ('termination_reason__in', ['LEFT_SCHOOL', 'MEMBER_REQUEST', 'RECORD_ERROR', 'MERGED'])), _connector='OR'), name='ck_membership_termination'),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.CheckConstraint(condition=models.Q(('requested_at__lte', models.F('started_at'))), name='ck_membership_request_before_start'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['status', 'due_date'], name='kutuphane_loan_st_due_idx'),
        ),
        migrations.AddConstraint(
            model_name='loan',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('status', 'OPEN')), fields=('copy',), name='uq_loan_open_per_copy'),
        ),
        migrations.AddConstraint(
            model_name='loan',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['OPEN', 'RETURNED'])), name='ck_loan_status'),
        ),
        migrations.AddConstraint(
            model_name='loan',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('returned_at__isnull', True), ('status', 'OPEN')), models.Q(('returned_at__isnull', False), ('status', 'RETURNED')), _connector='OR'), name='ck_loan_returned_at'),
        ),
        migrations.AddConstraint(
            model_name='loan',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('override_note', ''), ('override_reason', '')), models.Q(models.Q(('override_reason', ''), _negated=True), models.Q(('override_note', ''), _negated=True)), _connector='OR'), name='ck_loan_override_pair'),
        ),
        migrations.AddConstraint(
            model_name='loan',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('cardless', False), ('cardless_reason', '')), models.Q(('cardless', True), models.Q(('cardless_reason', ''), _negated=True)), _connector='OR'), name='ck_loan_cardless_reason'),
        ),
        migrations.AddConstraint(
            model_name='cardrevocation',
            constraint=models.CheckConstraint(condition=models.Q(('card_no_index', ''), _negated=True), name='ck_cardrevocation_index'),
        ),
        migrations.AddConstraint(
            model_name='cardrevocation',
            constraint=models.CheckConstraint(condition=models.Q(('reason__in', ['RENEWED', 'MERGED', 'DELETED'])), name='ck_cardrevocation_reason'),
        ),
    ]
