# Generated by Django 5.1.15 on 2026-09-24 23:12
#
# F7 — teslim (Delivery), kayıp/hasar dosyası (LossDamageCase), onarım kaydı
# (CopyRepair; Md. 19 bedel adımı iki adımdır: "Bedel belirlendi" ve "Bedel
# teslim alındı" — 25.09.2026 kullanıcı kararı, yayınlanmadan bu göçe işlendi);
# ödünce "Kayba dönüştü" durumu; yönetici kipi sürelerinin yeni
# aralıkları (boşta 1-15 dk, mutlak 5-120 dk; boşta ≤ mutlak). Elle eklenen tek
# adım `kip_surelerini_sinirla`dır: F2-F6'nın geniş aralığında (1-60 / 5-480)
# kaydedilmiş bir değer yeni kısıtı ve `full_clean`'i düşürmesin diye kısıttan
# ÖNCE aralığa çekilir.

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import shared.crypto
from decimal import Decimal
from django.db import migrations, models


def kip_surelerini_sinirla(apps, schema_editor):
    """Politika satırının kip sürelerini yeni aralığa çeker (geri göçte değerlere dokunulmaz)."""
    LibraryPolicy = apps.get_model("kutuphane", "LibraryPolicy")
    for satir in LibraryPolicy._base_manager.all():
        bosta = min(max(int(satir.idle_minutes), 1), 15)
        mutlak = min(max(int(satir.admin_max_minutes), 5), 120)
        bosta = min(bosta, mutlak)
        if (bosta, mutlak) != (satir.idle_minutes, satir.admin_max_minutes):
            LibraryPolicy._base_manager.filter(pk=satir.pk).update(
                idle_minutes=bosta, admin_max_minutes=mutlak
            )


class Migration(migrations.Migration):

    dependencies = [
        ('kutuphane', '0005_uyelik_ve_odunc'),
        ('okul', '0006_kutuphane_saatleri'),
    ]

    operations = [
        migrations.CreateModel(
            name='CopyRepair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='silinme')),
                ('sent_on', models.DateField(default=django.utils.timezone.localdate, verbose_name='onarıma gönderilme tarihi')),
                ('returned_on', models.DateField(blank=True, null=True, verbose_name='onarımdan dönüş tarihi')),
            ],
            options={
                'verbose_name': 'onarım kaydı',
                'verbose_name_plural': 'onarım kayıtları',
                'ordering': ['-sent_on', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='silinme')),
                ('recipient_kind', models.CharField(choices=[('SECTION', 'Sınıf kitaplığı'), ('TEACHER', 'Öğretmen')], max_length=8, verbose_name='teslim alan türü')),
                ('delivered_on', models.DateField(default=django.utils.timezone.localdate, verbose_name='teslim tarihi')),
                ('expected_return', models.DateField(blank=True, null=True, verbose_name='beklenen dönüş')),
                ('document_no', models.CharField(help_text='Teslim listesinin (E15) numarası; aynı toplu teslimin satırlarında aynıdır.', max_length=40, verbose_name='belge no')),
                ('status', models.CharField(choices=[('OPEN', 'Teslimde'), ('RETURNED', 'Geri alındı'), ('LOST_CONVERTED', 'Kayba dönüştü')], default='OPEN', max_length=16, verbose_name='durum')),
                ('returned_at', models.DateTimeField(blank=True, null=True, verbose_name='geri alma zamanı')),
                ('lost_at', models.DateTimeField(blank=True, null=True, verbose_name='kayba dönüşme zamanı')),
            ],
            options={
                'verbose_name': 'teslim',
                'verbose_name_plural': 'teslimler',
                'ordering': ['-delivered_on', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='LossDamageCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='silinme')),
                ('case_type', models.CharField(choices=[('LOST', 'Kayıp'), ('DAMAGED', 'Hasar')], max_length=8, verbose_name='tür')),
                ('responsible_note', shared.crypto.EncryptedTextField(blank=True, default='', help_text='Üye olmayan sorumlu ya da kısa açıklama. Sağlık ya da aile bilgisi yazmayın.', verbose_name='sorumlu notu')),
                ('reported_on', models.DateField(default=django.utils.timezone.localdate, verbose_name='tespit tarihi')),
                ('market_price', models.DecimalField(blank=True, decimal_places=2, help_text='Yalnız kayıt — program tahsilat yapmaz (Md. 19; yalnız ortaöğretim).', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='piyasa bedeli')),
                ('price_determined_at', models.DateTimeField(blank=True, help_text='“Bedel belirlendi” adımı; bedel düzeltilince yenilenir.', null=True, verbose_name='bedelin belirlendiği zaman')),
                ('price_received_at', models.DateTimeField(blank=True, help_text='“Bedel teslim alındı” adımı — yalnız kayıt; program tahsilat yapmaz.', null=True, verbose_name='bedelin teslim alındığı zaman')),
                ('resolution', models.CharField(choices=[('PENDING', 'Çözüm bekliyor'), ('PRICE_DETERMINED', 'Bedel belirlendi'), ('PRICE_RECEIVED', 'Bedel teslim alındı'), ('FOUND_RETURNED', 'Bulundu'), ('REPLACED_SAME', 'Aynısı temin edildi'), ('REPAIRED', 'Onarıldı'), ('CLOSED_SAME_REPURCHASED', 'Bedelle aynısı alındı'), ('CLOSED_OTHER_REPURCHASED', 'Bedelle başka eser alındı'), ('WRITE_OFF_PROPOSED', 'Kayıttan düşme önerildi'), ('CONVERTED_TO_LOSS', 'Kayba dönüştü')], default='PENDING', max_length=28, verbose_name='çözüm')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='çözüm tarihi')),
                ('write_off_proposed_at', models.DateTimeField(blank=True, help_text='Asıl kayıttan düşme TMY yoluyla yapılır (ayıklama ve sayım — F8/F9).', null=True, verbose_name='kayıttan düşme önerisi')),
            ],
            options={
                'verbose_name': 'kayıp/hasar dosyası',
                'verbose_name_plural': 'kayıp/hasar dosyaları',
                'ordering': ['-reported_on', '-pk'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='loan',
            name='ck_loan_status',
        ),
        migrations.RemoveConstraint(
            model_name='loan',
            name='ck_loan_returned_at',
        ),
        migrations.AddField(
            model_name='loan',
            name='lost_at',
            field=models.DateTimeField(blank=True, help_text='Kayıp bildirimiyle ödünç kapanınca yazılır (F7, Md. 19).', null=True, verbose_name='kayba dönüşme zamanı'),
        ),
        migrations.AlterField(
            model_name='librarypolicy',
            name='admin_max_minutes',
            field=models.PositiveSmallIntegerField(default=30, help_text='İşlem yapılsa da bu süre sonunda görevli kipine inilir (§4.4).', validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(120)], verbose_name='yönetici kipi mutlak süresi (dakika)'),
        ),
        migrations.AlterField(
            model_name='librarypolicy',
            name='idle_minutes',
            field=models.PositiveSmallIntegerField(default=3, help_text='Bu süre boyunca işlem yapılmazsa görevli kipine inilir (§4.4).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(15)], verbose_name='yönetici kipi boşta süresi (dakika)'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Açık'), ('RETURNED', 'İade edildi'), ('LOST_CONVERTED', 'Kayba dönüştü')], default='OPEN', max_length=16, verbose_name='durum'),
        ),
        migrations.RunPython(kip_surelerini_sinirla, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='librarypolicy',
            constraint=models.CheckConstraint(condition=models.Q(('idle_minutes__lte', models.F('admin_max_minutes'))), name='ck_librarypolicy_kip_sureleri', violation_error_message='Yönetici kipinin boşta süresi mutlak süresinden uzun olamaz.'),
        ),
        migrations.AddConstraint(
            model_name='loan',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['OPEN', 'RETURNED', 'LOST_CONVERTED'])), name='ck_loan_status'),
        ),
        migrations.AddConstraint(
            model_name='loan',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('lost_at__isnull', True), ('returned_at__isnull', True), ('status', 'OPEN')), models.Q(('lost_at__isnull', True), ('returned_at__isnull', False), ('status', 'RETURNED')), models.Q(('lost_at__isnull', False), ('returned_at__isnull', True), ('status', 'LOST_CONVERTED')), _connector='OR'), name='ck_loan_closing_times'),
        ),
        migrations.AddField(
            model_name='copyrepair',
            name='copy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='repairs', to='kutuphane.copy', verbose_name='nüsha'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='copy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='kutuphane.copy', verbose_name='nüsha'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='personnel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='library_deliveries', to='okul.personnel', verbose_name='öğretmen'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='library_deliveries', to='okul.classsection', verbose_name='şube (sınıf kitaplığı)'),
        ),
        migrations.AddField(
            model_name='lossdamagecase',
            name='copy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loss_damage_cases', to='kutuphane.copy', verbose_name='nüsha'),
        ),
        migrations.AddField(
            model_name='lossdamagecase',
            name='delivery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loss_damage_cases', to='kutuphane.delivery', verbose_name='teslim'),
        ),
        migrations.AddField(
            model_name='lossdamagecase',
            name='loan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loss_damage_cases', to='kutuphane.loan', verbose_name='ödünç'),
        ),
        migrations.AddField(
            model_name='lossdamagecase',
            name='membership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loss_damage_cases', to='kutuphane.membership', verbose_name='üyelik'),
        ),
        migrations.AddField(
            model_name='copyrepair',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repairs', to='kutuphane.lossdamagecase', verbose_name='hasar dosyası'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['status', 'recipient_kind'], name='kutuphane_delivery_st_idx'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['document_no'], name='kutuphane_delivery_doc_idx'),
        ),
        migrations.AddConstraint(
            model_name='delivery',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('status', 'OPEN')), fields=('copy',), name='uq_delivery_open_per_copy'),
        ),
        migrations.AddConstraint(
            model_name='delivery',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['OPEN', 'RETURNED', 'LOST_CONVERTED'])), name='ck_delivery_status'),
        ),
        migrations.AddConstraint(
            model_name='delivery',
            constraint=models.CheckConstraint(condition=models.Q(('recipient_kind__in', ['SECTION', 'TEACHER'])), name='ck_delivery_recipient_kind'),
        ),
        migrations.AddConstraint(
            model_name='delivery',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('personnel__isnull', True), ('recipient_kind', 'SECTION'), models.Q(('section__isnull', False), models.Q(('status', 'OPEN'), _negated=True), _connector='OR')), models.Q(('recipient_kind', 'TEACHER'), ('section__isnull', True), models.Q(('personnel__isnull', False), models.Q(('status', 'OPEN'), _negated=True), _connector='OR')), _connector='OR'), name='ck_delivery_recipient'),
        ),
        migrations.AddConstraint(
            model_name='delivery',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('lost_at__isnull', True), ('returned_at__isnull', True), ('status', 'OPEN')), models.Q(('lost_at__isnull', True), ('returned_at__isnull', False), ('status', 'RETURNED')), models.Q(('lost_at__isnull', False), ('returned_at__isnull', True), ('status', 'LOST_CONVERTED')), _connector='OR'), name='ck_delivery_closing_times'),
        ),
        migrations.AddConstraint(
            model_name='delivery',
            constraint=models.CheckConstraint(condition=models.Q(('expected_return__isnull', True), ('expected_return__gte', models.F('delivered_on')), _connector='OR'), name='ck_delivery_expected_return'),
        ),
        migrations.AddConstraint(
            model_name='delivery',
            constraint=models.CheckConstraint(condition=models.Q(('document_no', ''), _negated=True), name='ck_delivery_document_no'),
        ),
        migrations.AddIndex(
            model_name='lossdamagecase',
            index=models.Index(fields=['resolution', 'case_type'], name='kutuphane_ldc_res_idx'),
        ),
        migrations.AddConstraint(
            model_name='lossdamagecase',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('resolution__in', ('PENDING', 'PRICE_DETERMINED', 'PRICE_RECEIVED'))), fields=('copy',), name='uq_lossdamagecase_open_per_copy'),
        ),
        migrations.AddConstraint(
            model_name='lossdamagecase',
            constraint=models.CheckConstraint(condition=models.Q(('case_type__in', ['LOST', 'DAMAGED'])), name='ck_lossdamagecase_type'),
        ),
        migrations.AddConstraint(
            model_name='lossdamagecase',
            constraint=models.CheckConstraint(condition=models.Q(('resolution__in', ['PENDING', 'PRICE_DETERMINED', 'PRICE_RECEIVED', 'FOUND_RETURNED', 'REPLACED_SAME', 'REPAIRED', 'CLOSED_SAME_REPURCHASED', 'CLOSED_OTHER_REPURCHASED', 'WRITE_OFF_PROPOSED', 'CONVERTED_TO_LOSS'])), name='ck_lossdamagecase_resolution'),
        ),
        migrations.AddConstraint(
            model_name='lossdamagecase',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('resolution__in', ('PENDING', 'PRICE_DETERMINED', 'PRICE_RECEIVED')), ('resolved_at__isnull', True)), models.Q(models.Q(('resolution__in', ('PENDING', 'PRICE_DETERMINED', 'PRICE_RECEIVED')), _negated=True), ('resolved_at__isnull', False)), _connector='OR'), name='ck_lossdamagecase_resolved_at'),
        ),
        migrations.AddConstraint(
            model_name='lossdamagecase',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('resolution__in', ('CLOSED_OTHER_REPURCHASED', 'WRITE_OFF_PROPOSED')), ('write_off_proposed_at__isnull', False)), models.Q(models.Q(('resolution__in', ('CLOSED_OTHER_REPURCHASED', 'WRITE_OFF_PROPOSED')), _negated=True), ('write_off_proposed_at__isnull', True)), _connector='OR'), name='ck_lossdamagecase_write_off'),
        ),
        migrations.AddConstraint(
            model_name='lossdamagecase',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('resolution__in', ('PRICE_DETERMINED', 'PRICE_RECEIVED', 'CLOSED_SAME_REPURCHASED', 'CLOSED_OTHER_REPURCHASED')), _negated=True), ('market_price__isnull', False), _connector='OR'), name='ck_lossdamagecase_price'),
        ),
        migrations.AddConstraint(
            model_name='lossdamagecase',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('market_price__isnull', True), ('price_determined_at__isnull', True)), models.Q(('market_price__isnull', False), ('price_determined_at__isnull', False)), _connector='OR'), name='ck_lossdamagecase_price_determined'),
        ),
        migrations.AddConstraint(
            model_name='lossdamagecase',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('price_received_at__isnull', False), ('resolution__in', ('PRICE_RECEIVED', 'CLOSED_SAME_REPURCHASED', 'CLOSED_OTHER_REPURCHASED'))), models.Q(models.Q(('resolution__in', ('PRICE_RECEIVED', 'CLOSED_SAME_REPURCHASED', 'CLOSED_OTHER_REPURCHASED')), _negated=True), ('price_received_at__isnull', True)), ('resolution', 'CONVERTED_TO_LOSS'), _connector='OR'), name='ck_lossdamagecase_price_received'),
        ),
        migrations.AddConstraint(
            model_name='lossdamagecase',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('resolution', 'FOUND_RETURNED'), _negated=True), ('case_type', 'LOST'), _connector='OR'), name='ck_lossdamagecase_found_lost'),
        ),
        migrations.AddConstraint(
            model_name='lossdamagecase',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('resolution', 'REPAIRED'), _negated=True), ('case_type', 'DAMAGED'), _connector='OR'), name='ck_lossdamagecase_repaired_damaged'),
        ),
        migrations.AddConstraint(
            model_name='lossdamagecase',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('resolution', 'CONVERTED_TO_LOSS'), _negated=True), ('case_type', 'DAMAGED'), _connector='OR'), name='ck_lossdamagecase_converted_damaged'),
        ),
        migrations.AddConstraint(
            model_name='copyrepair',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('returned_on__isnull', True)), fields=('copy',), name='uq_copyrepair_open_per_copy'),
        ),
        migrations.AddConstraint(
            model_name='copyrepair',
            constraint=models.CheckConstraint(condition=models.Q(('returned_on__isnull', True), ('returned_on__gte', models.F('sent_on')), _connector='OR'), name='ck_copyrepair_dates'),
        ),
    ]
