# Generated by Django 5.1.15 on 2026-09-25 06:41
#
# F8 — ayıklama teklifi ve kalemleri (Md. 12/1; D15 — kalem silme, teklifi geri
# çekme; E7 tablosu gerekçeden TMY yoluna DB kısıtıdır: 10/1-b gerekçeli kalem 28
# yoluna gidemez, devir yalnız düzeye uygunsuzlukla), el yazması ve nadir eserler
# listesi (Md. 12/2; D14 — komisyon kararı bağı) ve yıl sonu kütüphane raporu
# (Md. 12/1, E9 — kişisiz, sonlandırılınca dondurulur). Veri göçü yoktur: tablolar
# yenidir, var olan satırlara dokunulmaz. F8 düzeltme turu (25.09.2026, birleşmeden
# önce bu göçe eklendi): kalem düzeyinde imha kararı (TMY 28/5) ve geri çekilen
# teklifin önceki komisyon kararı izi. 25.09.2026 kullanıcı kararları (birleşmeden
# önce bu göçe eklendi): kayıp/hasar dosyasına yeni çözüm "Bulundu (bedel teslim
# alınmıştı)" (F8 ekleri 14; 0006'nın dört kısıtı yeni çözümle yeniden kurulur) ve
# kalemin kayıp/hasar dosyası bağı kalktı (F8 ekleri 34: öneri ayıklamaya konmaz).

import django.db.models.deletion
import shared.crypto
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kutuphane', '0006_teslim_kayip_onarim'),
        ('okul', '0006_kutuphane_saatleri'),
    ]

    operations = [
        migrations.CreateModel(
            name='RareWorksSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='silinme')),
                ('status', models.CharField(choices=[('DRAFT', 'Hazırlanıyor'), ('SENT', 'Genel Müdürlüğe gönderildi')], default='DRAFT', max_length=8, verbose_name='durum')),
                ('sent_on', models.DateField(blank=True, null=True, verbose_name='Genel Müdürlüğe gönderim tarihi')),
                ('sent_document_no', models.CharField(blank=True, default='', max_length=40, verbose_name='gönderme yazısının sayısı')),
                ('notes', models.TextField(blank=True, default='', verbose_name='notlar')),
                ('commission_decision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rare_works_submissions', to='kutuphane.commissiondecision', verbose_name='komisyon kararı')),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rare_works_submissions', to='okul.schoolyear', verbose_name='ders yılı')),
            ],
            options={
                'verbose_name': 'el yazması ve nadir eserler listesi',
                'verbose_name_plural': 'el yazması ve nadir eserler listeleri',
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='RareWorksSubmissionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='silinme')),
                ('copy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rare_submission_items', to='kutuphane.copy', verbose_name='nüsha')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='kutuphane.rareworkssubmission', verbose_name='liste')),
            ],
            options={
                'verbose_name': 'nadir eser satırı',
                'verbose_name_plural': 'nadir eser satırları',
                'ordering': ['submission', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='WeedingBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='silinme')),
                ('status', models.CharField(choices=[('DRAFT', 'Taslak'), ('SUBMITTED', 'Komisyona sunuldu'), ('DECIDED', 'Komisyon kararı bağlandı'), ('APPROVED', 'Harcama yetkilisi onayladı'), ('APPLIED', 'Uygulandı'), ('CANCELLED', 'İptal edildi')], default='DRAFT', max_length=12, verbose_name='durum')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='komisyona sunulma zamanı')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='kararın bağlandığı zaman')),
                ('tmy_commission_members', shared.crypto.EncryptedTextField(blank=True, default='', help_text='Kayıttan düşme teklif ve onay tutanağını imzalayan komisyon (TMY 10/1-e, 28/1); satır başına bir kişi.', verbose_name='TMY komisyonu üyeleri')),
                ('approved_by_name', shared.crypto.EncryptedCharField(blank=True, default='', help_text='Kayıttan düşmeyi ve devri onaylayan harcama yetkilisi.', max_length=120, verbose_name='harcama yetkilisi adı')),
                ('approved_on', models.DateField(blank=True, null=True, verbose_name='onay tarihi')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='onayın işlendiği zaman')),
                ('destruction_decided', models.BooleanField(default=False, help_text='TMY 28/5: komisyon imhaya karar verdiyse imha tutanağı düzenlenir; kararın kapsadığı kalemler kalem düzeyinde işaretlidir.', verbose_name='imha kararı')),
                ('withdrawn_items', models.JSONField(blank=True, null=True, verbose_name='geri çekilmeden önce kararın kapsadığı kalemler')),
                ('applied_at', models.DateTimeField(blank=True, null=True, verbose_name='uygulanma zamanı')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='iptal zamanı')),
                ('cancel_reason', models.CharField(blank=True, default='', max_length=255, verbose_name='iptal gerekçesi')),
                ('notes', models.TextField(blank=True, default='', verbose_name='notlar')),
                ('commission_decision', models.ForeignKey(blank=True, help_text='Seçim ve Ayıklama Komisyonunun “Ayıklama” türündeki kararı (Md. 12/1).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='weeding_batches', to='kutuphane.commissiondecision', verbose_name='komisyon kararı')),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='weeding_batches', to='okul.schoolyear', verbose_name='ders yılı')),
                ('withdrawn_decision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='kutuphane.commissiondecision', verbose_name='geri çekilmeden önceki komisyon kararı')),
            ],
            options={
                'verbose_name': 'ayıklama teklifi',
                'verbose_name_plural': 'ayıklama teklifleri',
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='WeedingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='silinme')),
                ('reason', models.CharField(choices=[('WORN', 'Aşırı kullanımdan yıpranmış'), ('OBSOLETE', 'Bilimsel değeri kalmamış'), ('LEVEL_MISMATCH', 'Kurumun düzeyine uygun değil'), ('CRITERIA_MISMATCH', '10. maddedeki ölçütlere uygun değil')], max_length=20, verbose_name='gerekçe')),
                ('criterion', models.CharField(blank=True, choices=[('10_1_A', 'Türk millî eğitiminin genel amaçları ve temel ilkelerine uygun değil'), ('10_1_B', 'Öğrencilerin yaş ve gelişim düzeylerine uygun değil'), ('10_1_C', 'Millî, manevi, kültürel, ahlâki ve insani değerlere uygun değil'), ('10_1_CH', 'Dengeli ve sağlıklı kişilik gelişimini desteklemiyor'), ('10_1_D', 'Türkçenin doğru ve güzel kullanımını desteklemiyor'), ('10_1_E', 'Eleştirel ve özgün düşünme becerilerini desteklemiyor'), ('10_1_F', 'Farklı okuryazarlıkları desteklemiyor'), ('10_4', 'Kütüphanede bulundurulamaz (Md. 10/4)')], default='', help_text='Yalnız “10. maddedeki ölçütlere uygun değil” gerekçesinde.', max_length=8, verbose_name='uyulmayan ölçüt')),
                ('tmy_path', models.CharField(choices=[('TMY_27', 'Kullanılmaz hâle gelme nedeniyle kayıttan düşme (TMY 27/1)'), ('TMY_28', 'Hurdaya ayırma nedeniyle kayıttan düşme (TMY 28)'), ('TMY_24_2', 'Başka bir MEB okuluna devir (TMY 24/2)'), ('TMY_31', 'Başka bir kamu idaresine bedelsiz devir (TMY 31)')], max_length=10, verbose_name='TMY yolu')),
                ('transfer_target', models.CharField(blank=True, default='', help_text='Yalnız devirde.', max_length=255, verbose_name='devralacak okul ya da kurum')),
                ('state', models.CharField(choices=[('PROPOSED', 'Teklif listesinde'), ('KEPT_BY_COMMISSION', 'Komisyon ayıklanmasına karar vermedi'), ('NOT_APPROVED', 'Onaylanmadı'), ('APPLIED', 'Uygulandı')], default='PROPOSED', max_length=20, verbose_name='kalem durumu')),
                ('exclusion_reason', models.CharField(blank=True, default='', max_length=255, verbose_name='ayıklanmama gerekçesi')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='kutuphane.weedingbatch', verbose_name='teklif')),
                ('copy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='weeding_items', to='kutuphane.copy', verbose_name='nüsha')),
                ('destruction_decided', models.BooleanField(default=False, help_text='TMY 28/5: komisyonun imhaya karar verdiği hurdaya ayırma kalemi.', verbose_name='imha kararı')),
            ],
            options={
                'verbose_name': 'ayıklama kalemi',
                'verbose_name_plural': 'ayıklama kalemleri',
                'ordering': ['batch', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='AnnualLibraryReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='silinme')),
                ('document_date', models.DateField(blank=True, null=True, verbose_name='tarih')),
                ('document_no', models.CharField(blank=True, default='', max_length=40, verbose_name='sayı')),
                ('findings', models.TextField(blank=True, default='', help_text='Kaynakların durumu ve öneriler. Kişi adı yazmayın.', verbose_name='tespit edilen hususlar')),
                ('stats', models.JSONField(blank=True, null=True, verbose_name='dondurulmuş sayılar')),
                ('finalized_at', models.DateTimeField(blank=True, null=True, verbose_name='sonlandırılma zamanı')),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='library_reviews', to='okul.schoolyear', verbose_name='ders yılı')),
            ],
            options={
                'verbose_name': 'yıl sonu kütüphane raporu',
                'verbose_name_plural': 'yıl sonu kütüphane raporları',
                'ordering': ['-school_year__start_date', '-pk'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('school_year',), name='uq_annualreview_school_year'), models.CheckConstraint(condition=models.Q(models.Q(('finalized_at__isnull', True), ('stats__isnull', True)), models.Q(('finalized_at__isnull', False), ('stats__isnull', False)), _connector='OR'), name='ck_annualreview_finalized')],
            },
        ),
        migrations.AddConstraint(
            model_name='rareworkssubmission',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['DRAFT', 'SENT'])), name='ck_rareworks_status'),
        ),
        migrations.AddConstraint(
            model_name='rareworkssubmission',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('commission_decision__isnull', False), ('sent_on__isnull', False), ('status', 'SENT')), models.Q(('sent_on__isnull', True), ('status', 'DRAFT')), _connector='OR'), name='ck_rareworks_sent'),
        ),
        migrations.AddConstraint(
            model_name='rareworkssubmissionitem',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('submission', 'copy'), name='uq_rareworksitem_copy'),
        ),
        migrations.AddIndex(
            model_name='weedingbatch',
            index=models.Index(fields=['status', 'school_year'], name='kutuphane_wb_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='weedingbatch',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['DRAFT', 'SUBMITTED', 'DECIDED', 'APPROVED', 'APPLIED', 'CANCELLED'])), name='ck_weedingbatch_status'),
        ),
        migrations.AddConstraint(
            model_name='weedingbatch',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'DRAFT'), ('submitted_at__isnull', True)), models.Q(('status__in', ['SUBMITTED', 'DECIDED', 'APPROVED', 'APPLIED']), ('submitted_at__isnull', False)), ('status', 'CANCELLED'), _connector='OR'), name='ck_weedingbatch_submitted'),
        ),
        migrations.AddConstraint(
            model_name='weedingbatch',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('commission_decision__isnull', True), ('decided_at__isnull', True), ('status__in', ['DRAFT', 'SUBMITTED'])), models.Q(('commission_decision__isnull', False), ('decided_at__isnull', False), ('status__in', ['DECIDED', 'APPROVED', 'APPLIED'])), ('status', 'CANCELLED'), _connector='OR'), name='ck_weedingbatch_decision'),
        ),
        migrations.AddConstraint(
            model_name='weedingbatch',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('approved_at__isnull', True), ('approved_by_name', ''), ('approved_on__isnull', True), ('destruction_decided', False), ('status__in', ['DRAFT', 'SUBMITTED', 'DECIDED'])), models.Q(('approved_at__isnull', False), ('approved_on__isnull', False), ('status__in', ['APPROVED', 'APPLIED']), models.Q(('approved_by_name', ''), _negated=True)), ('status', 'CANCELLED'), _connector='OR'), name='ck_weedingbatch_approval'),
        ),
        migrations.AddConstraint(
            model_name='weedingbatch',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('applied_at__isnull', False), ('status', 'APPLIED')), models.Q(models.Q(('status', 'APPLIED'), _negated=True), ('applied_at__isnull', True)), _connector='OR'), name='ck_weedingbatch_applied_at'),
        ),
        migrations.AddConstraint(
            model_name='weedingbatch',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('cancelled_at__isnull', False), ('status', 'CANCELLED')), models.Q(models.Q(('status', 'CANCELLED'), _negated=True), ('cancelled_at__isnull', True)), _connector='OR'), name='ck_weedingbatch_cancelled_at'),
        ),
        migrations.AddConstraint(
            model_name='weedingitem',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('batch', 'copy'), name='uq_weedingitem_copy_per_batch'),
        ),
        migrations.AddConstraint(
            model_name='weedingitem',
            constraint=models.CheckConstraint(condition=models.Q(('reason__in', ['WORN', 'OBSOLETE', 'LEVEL_MISMATCH', 'CRITERIA_MISMATCH'])), name='ck_weedingitem_reason'),
        ),
        migrations.AddConstraint(
            model_name='weedingitem',
            constraint=models.CheckConstraint(condition=models.Q(('state__in', ['PROPOSED', 'KEPT_BY_COMMISSION', 'NOT_APPROVED', 'APPLIED'])), name='ck_weedingitem_state'),
        ),
        migrations.AddConstraint(
            model_name='weedingitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('reason', 'WORN'), ('tmy_path__in', ['TMY_27', 'TMY_28'])), models.Q(('reason', 'OBSOLETE'), ('tmy_path__in', ['TMY_28'])), models.Q(('reason', 'LEVEL_MISMATCH'), ('tmy_path__in', ['TMY_24_2', 'TMY_31'])), models.Q(('reason', 'CRITERIA_MISMATCH'), ('tmy_path__in', ['TMY_28'])), _connector='OR'), name='ck_weedingitem_e7_path'),
        ),
        migrations.AddConstraint(
            model_name='weedingitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('criterion__in', ['10_1_A', '10_1_C', '10_1_CH', '10_1_D', '10_1_E', '10_1_F', '10_4']), ('reason', 'CRITERIA_MISMATCH')), models.Q(models.Q(('reason', 'CRITERIA_MISMATCH'), _negated=True), ('criterion', '')), _connector='OR'), name='ck_weedingitem_criterion'),
        ),
        migrations.AddConstraint(
            model_name='weedingitem',
            constraint=models.CheckConstraint(condition=models.Q(('tmy_path__in', ['TMY_24_2', 'TMY_31']), ('transfer_target', ''), _connector='OR'), name='ck_weedingitem_transfer_target'),
        ),
        migrations.AddConstraint(
            model_name='weedingitem',
            constraint=models.CheckConstraint(condition=models.Q(('destruction_decided', False), ('tmy_path', 'TMY_28'), _connector='OR'), name='ck_weedingitem_destruction'),
        ),
        migrations.AddConstraint(
            model_name='weedingitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('state__in', ['KEPT_BY_COMMISSION', 'NOT_APPROVED']), models.Q(('exclusion_reason', ''), _negated=True)), models.Q(models.Q(('state__in', ['KEPT_BY_COMMISSION', 'NOT_APPROVED']), _negated=True), ('exclusion_reason', '')), _connector='OR'), name='ck_weedingitem_exclusion'),
        ),
        # 25.09.2026 kullanıcı kararı (tasarım F8 ekleri 14): bedeli teslim alınmış kayıp
        # dosyasında kitap bulunursa yeni çözüm "Bulundu (bedel teslim alınmıştı)". Bedel
        # yoludur ve bedel teslim kaydını taşır; "Bulundu" gibi yalnız kayıpta durur.
        migrations.RemoveConstraint(
            model_name='lossdamagecase',
            name='ck_lossdamagecase_resolution',
        ),
        migrations.RemoveConstraint(
            model_name='lossdamagecase',
            name='ck_lossdamagecase_price',
        ),
        migrations.RemoveConstraint(
            model_name='lossdamagecase',
            name='ck_lossdamagecase_price_received',
        ),
        migrations.RemoveConstraint(
            model_name='lossdamagecase',
            name='ck_lossdamagecase_found_lost',
        ),
        migrations.AlterField(
            model_name='lossdamagecase',
            name='resolution',
            field=models.CharField(choices=[('PENDING', 'Çözüm bekliyor'), ('PRICE_DETERMINED', 'Bedel belirlendi'), ('PRICE_RECEIVED', 'Bedel teslim alındı'), ('FOUND_RETURNED', 'Bulundu'), ('REPLACED_SAME', 'Aynısı temin edildi'), ('REPAIRED', 'Onarıldı'), ('CLOSED_SAME_REPURCHASED', 'Bedelle aynısı alındı'), ('CLOSED_OTHER_REPURCHASED', 'Bedelle başka eser alındı'), ('FOUND_AFTER_PRICE', 'Bulundu (bedel teslim alınmıştı)'), ('WRITE_OFF_PROPOSED', 'Kayıttan düşme önerildi'), ('CONVERTED_TO_LOSS', 'Kayba dönüştü')], default='PENDING', max_length=28, verbose_name='çözüm'),
        ),
        # Kayıttan düşme önerisi ayıklamaya konmaz, sayımda düşülür (F8 ekleri 34).
        migrations.AlterField(
            model_name='lossdamagecase',
            name='write_off_proposed_at',
            field=models.DateTimeField(blank=True, help_text='Asıl kayıttan düşme sayımda, TMY 27/1 yoluyla yapılır (F9).', null=True, verbose_name='kayıttan düşme önerisi'),
        ),
        migrations.AddConstraint(
            model_name='lossdamagecase',
            constraint=models.CheckConstraint(condition=models.Q(('resolution__in', ['PENDING', 'PRICE_DETERMINED', 'PRICE_RECEIVED', 'FOUND_RETURNED', 'REPLACED_SAME', 'REPAIRED', 'CLOSED_SAME_REPURCHASED', 'CLOSED_OTHER_REPURCHASED', 'FOUND_AFTER_PRICE', 'WRITE_OFF_PROPOSED', 'CONVERTED_TO_LOSS'])), name='ck_lossdamagecase_resolution'),
        ),
        migrations.AddConstraint(
            model_name='lossdamagecase',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('resolution__in', ('PRICE_DETERMINED', 'PRICE_RECEIVED', 'CLOSED_SAME_REPURCHASED', 'CLOSED_OTHER_REPURCHASED', 'FOUND_AFTER_PRICE')), _negated=True), ('market_price__isnull', False), _connector='OR'), name='ck_lossdamagecase_price'),
        ),
        migrations.AddConstraint(
            model_name='lossdamagecase',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('price_received_at__isnull', False), ('resolution__in', ('PRICE_RECEIVED', 'CLOSED_SAME_REPURCHASED', 'CLOSED_OTHER_REPURCHASED', 'FOUND_AFTER_PRICE'))), models.Q(models.Q(('resolution__in', ('PRICE_RECEIVED', 'CLOSED_SAME_REPURCHASED', 'CLOSED_OTHER_REPURCHASED', 'FOUND_AFTER_PRICE')), _negated=True), ('price_received_at__isnull', True)), ('resolution', 'CONVERTED_TO_LOSS'), _connector='OR'), name='ck_lossdamagecase_price_received'),
        ),
        migrations.AddConstraint(
            model_name='lossdamagecase',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('resolution__in', ('FOUND_RETURNED', 'FOUND_AFTER_PRICE')), _negated=True), ('case_type', 'LOST'), _connector='OR'), name='ck_lossdamagecase_found_lost'),
        ),
    ]
