# Generated by Django 5.1.15 on 2026-09-25 14:42
#
# F9 — sayım (TMY 32; tasarım §6.2, §9-10, §9-11): sayım ve kalemleri (başlangıçta
# anlık görüntü; iki AYRI seçenek — TMY 32/3 durdurması ve sayım için hizmet arası;
# kurul ve harcama yetkilisi adları şifreli; kalem kişisizdir; D16: sayım fazlasının
# kodu `surplus_barcode`'dadır). Nüsha durumlarına "Hasar (kayıttan düşüldü)" eklenir
# (F8 ekleri 34: hasar önerisi TMY 27/1 + 10/1-e yolundan sayımda düşülür). Veri göçü
# yoktur: tablolar yenidir, var olan satırlara dokunulmaz. Yayınlanmadan yerinde
# düzenlendi (F9 ekleri K2, K3 — 25.09.2026): onarımdaki nüsha için kurul seçimi
# (`repair_basis`), sınıf kitaplığında "Kayda göre alınır" kalktı.

import django.core.validators
import django.db.models.deletion
import shared.crypto
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kutuphane', '0007_ayiklama_nadir_eser_yil_raporu'),
        ('okul', '0006_kutuphane_saatleri'),
    ]

    operations = [
        migrations.AlterField(
            model_name='copy',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Rafta'), ('ON_LOAN', 'Ödünçte'), ('DELIVERED', 'Sınıf kitaplığında'), ('IN_REPAIR', 'Onarımda'), ('LOST', 'Kayıp'), ('WITHDRAWN_WEEDED', 'Ayıklandı (kayıttan düşüldü)'), ('WITHDRAWN_MISSING', 'Sayım noksanı (kayıttan düşüldü)'), ('WITHDRAWN_LOST', 'Kayıp (kayıttan düşüldü)'), ('WITHDRAWN_DAMAGED', 'Hasar (kayıttan düşüldü)'), ('TRANSFERRED', 'Devredildi')], default='AVAILABLE', max_length=20, verbose_name='durum'),
        ),
        migrations.CreateModel(
            name='StockTake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='silinme')),
                ('fiscal_year', models.PositiveSmallIntegerField(blank=True, help_text='TMY 34/1 büyüklüklerinin yılı; boşsa sayımın başladığı yıl yazılır.', null=True, validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2999)], verbose_name='mali yıl')),
                ('status', models.CharField(choices=[('DRAFT', 'Taslak'), ('IN_PROGRESS', 'Sürüyor'), ('COMPLETED', 'Tamamlandı'), ('APPROVED', 'Onaylandı'), ('CANCELLED', 'İptal edildi')], default='DRAFT', max_length=12, verbose_name='durum')),
                ('open_slot', models.BooleanField(default=True, null=True, verbose_name='canlı sayım işareti')),
                ('committee_chair', shared.crypto.EncryptedCharField(blank=True, default='', help_text='Harcama yetkilisi ya da görevlendirdiği kişi (TMY 32/2).', max_length=120, verbose_name='kurul başkanı')),
                ('committee_property_officer', shared.crypto.EncryptedCharField(blank=True, default='', help_text='Sayım kurulunda taşınır kayıt yetkilisi de bulunur (TMY 32/2).', max_length=120, verbose_name='taşınır kayıt yetkilisi')),
                ('committee_members', shared.crypto.EncryptedTextField(blank=True, default='', help_text='Diğer üyeler; satır başına bir kişi. Kurul en az üç kişidir (TMY 32/2).', verbose_name='kurul üyeleri')),
                ('tmy_stop', models.BooleanField(default=False, verbose_name='TMY 32/3 durdurması')),
                ('tmy_stop_requested_on', models.DateField(blank=True, null=True, verbose_name='kurulun durdurma talebinin tarihi')),
                ('tmy_stop_by_name', shared.crypto.EncryptedCharField(blank=True, default='', max_length=120, verbose_name='durduran harcama yetkilisi')),
                ('tmy_stop_on', models.DateField(blank=True, null=True, verbose_name='durdurma tarihi')),
                ('service_pause', models.BooleanField(default=False, verbose_name='sayım için hizmet arası')),
                ('service_pause_decision', models.CharField(blank=True, default='', help_text='Okul kararının tarihi ve sayısı (isteğe bağlı). Kişi adı yazmayın.', max_length=120, verbose_name='hizmet arası okul kararı')),
                ('loan_basis', models.CharField(choices=[('LIBRARY', 'Kütüphanede sayılır'), ('COLLECT', 'Sayımdan önce toplanır'), ('IN_PLACE', 'Yerinde sayılır'), ('BY_RECORD', 'Kayda göre alınır')], default='BY_RECORD', max_length=10, verbose_name='ödünçteki nüsha')),
                ('section_delivery_basis', models.CharField(choices=[('LIBRARY', 'Kütüphanede sayılır'), ('COLLECT', 'Sayımdan önce toplanır'), ('IN_PLACE', 'Yerinde sayılır'), ('BY_RECORD', 'Kayda göre alınır')], default='IN_PLACE', max_length=10, verbose_name='sınıf kitaplığındaki nüsha')),
                ('teacher_delivery_basis', models.CharField(choices=[('LIBRARY', 'Kütüphanede sayılır'), ('COLLECT', 'Sayımdan önce toplanır'), ('IN_PLACE', 'Yerinde sayılır'), ('BY_RECORD', 'Kayda göre alınır')], default='BY_RECORD', max_length=10, verbose_name='öğretmene teslim edilen nüsha')),
                ('repair_basis', models.CharField(choices=[('LIBRARY', 'Kütüphanede sayılır'), ('COLLECT', 'Sayımdan önce toplanır'), ('IN_PLACE', 'Yerinde sayılır'), ('BY_RECORD', 'Kayda göre alınır')], default='BY_RECORD', help_text='Sayımdan önce geri alınır ya da kayda göre alınır — onarımda (sayım kurulunun kararı; F9 ekleri K2).', max_length=10, verbose_name='onarımdaki nüsha')),
                ('round', models.PositiveSmallIntegerField(default=1, help_text='2: farklı çıkanların yeniden sayımı (TMY 32/6).', verbose_name='sayım turu')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='başlama zamanı (anlık görüntü)')),
                ('round2_started_at', models.DateTimeField(blank=True, null=True, verbose_name='ikinci sayımın başlangıcı')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='tamamlanma zamanı')),
                ('approved_by_name', shared.crypto.EncryptedCharField(blank=True, default='', help_text='Noksanın ve hasar önerilerinin kayıttan düşülmesini onaylar (TMY 10/1-e).', max_length=120, verbose_name='onaylayan harcama yetkilisi')),
                ('approved_on', models.DateField(blank=True, null=True, verbose_name='onay tarihi')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='onayın işlendiği zaman')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='iptal zamanı')),
                ('cancel_reason', models.CharField(blank=True, default='', max_length=255, verbose_name='iptal gerekçesi')),
                ('notes', models.TextField(blank=True, default='', help_text='Sayıma ilişkin notlar. Kişi adı yazmayın.', verbose_name='notlar')),
                ('surplus_acquisition', models.ForeignKey(blank=True, help_text='Onayda fazlanın kayda alındığı “Sayım fazlası (kayda giriş)” edinimi.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='kutuphane.acquisition', verbose_name='sayım fazlası edinimi')),
            ],
            options={
                'verbose_name': 'sayım',
                'verbose_name_plural': 'sayımlar',
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='StockTakeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='silinme')),
                ('expected_status', models.CharField(blank=True, choices=[('AVAILABLE', 'Rafta'), ('ON_LOAN', 'Ödünçte'), ('DELIVERED', 'Sınıf kitaplığında'), ('IN_REPAIR', 'Onarımda'), ('LOST', 'Kayıp'), ('WITHDRAWN_WEEDED', 'Ayıklandı (kayıttan düşüldü)'), ('WITHDRAWN_MISSING', 'Sayım noksanı (kayıttan düşüldü)'), ('WITHDRAWN_LOST', 'Kayıp (kayıttan düşüldü)'), ('WITHDRAWN_DAMAGED', 'Hasar (kayıttan düşüldü)'), ('TRANSFERRED', 'Devredildi')], default='', max_length=20, verbose_name='kayda göre durum (anlık görüntü)')),
                ('delivery_kind', models.CharField(blank=True, choices=[('SECTION', 'Sınıf kitaplığı'), ('TEACHER', 'Öğretmen')], default='', max_length=8, verbose_name='teslim türü (anlık görüntü)')),
                ('basis', models.CharField(blank=True, choices=[('LIBRARY', 'Kütüphanede sayılır'), ('COLLECT', 'Sayımdan önce toplanır'), ('IN_PLACE', 'Yerinde sayılır'), ('BY_RECORD', 'Kayda göre alınır')], default='', max_length=10, verbose_name='nasıl sayılır')),
                ('result', models.CharField(choices=[('PENDING', 'Sayılmadı'), ('FOUND', 'Bulundu'), ('BY_RECORD', 'Kayda göre alındı'), ('MISSING', 'Noksan'), ('SURPLUS', 'Fazla'), ('EXITED', 'Sayım sırasında kayıttan çıktı')], default='PENDING', max_length=10, verbose_name='sonuç')),
                ('found_in_round', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='bulunduğu tur')),
                ('found_via', models.CharField(blank=True, choices=[('SCAN', 'Okutuldu'), ('RETURN', 'Sayım sırasında kütüphaneye döndü')], default='', max_length=8, verbose_name='nasıl bulundu')),
                ('scanned_at', models.DateTimeField(blank=True, null=True, verbose_name='okutma zamanı')),
                ('basis_fallback', models.BooleanField(default=False, help_text='Toplanması ya da kütüphanede sayılması gereken nüsha açık ödünçte, öğretmende ya da onarımda.', verbose_name='sayılamadı — kayda göre alındı')),
                ('status_at_completion', models.CharField(blank=True, choices=[('AVAILABLE', 'Rafta'), ('ON_LOAN', 'Ödünçte'), ('DELIVERED', 'Sınıf kitaplığında'), ('IN_REPAIR', 'Onarımda'), ('LOST', 'Kayıp'), ('WITHDRAWN_WEEDED', 'Ayıklandı (kayıttan düşüldü)'), ('WITHDRAWN_MISSING', 'Sayım noksanı (kayıttan düşüldü)'), ('WITHDRAWN_LOST', 'Kayıp (kayıttan düşüldü)'), ('WITHDRAWN_DAMAGED', 'Hasar (kayıttan düşüldü)'), ('TRANSFERRED', 'Devredildi')], default='', help_text='Onayda yeniden doğrulama bununla karşılaştırır (D17).', max_length=20, verbose_name='tamamlanırken durum')),
                ('damage_write_off', models.BooleanField(default=False, help_text='Hasar dosyasında kayıttan düşme önerilen, kütüphanede bulunan nüsha.', verbose_name='hasar önerisi (TMY 27/1)')),
                ('outcome', models.CharField(blank=True, choices=[('WRITTEN_OFF', 'Kayıttan düşüldü'), ('NOT_APPROVED', 'Onaylanmadı'), ('STATE_CHANGED', 'Onayda durumu değişmişti — düşülmedi'), ('RECONCILED', 'Kayıp kaydı kapandı'), ('ENTERED', 'Kayda alındı'), ('NOT_ENTERED', 'Kayda alınmadı')], default='', max_length=14, verbose_name='onay sonucu')),
                ('write_off_path', models.CharField(blank=True, choices=[('MISSING_32_7', 'Sayım noksanı (TMY 32/7)'), ('DAMAGE_27_1', 'Kullanılmaz hâle gelme — hasar (TMY 27/1, 10/1-e)')], default='', max_length=14, verbose_name='kayıttan düşme yolu')),
                ('outcome_note', models.CharField(blank=True, default='', help_text='Onaylanmama gerekçesi ya da onaydaki durum. Kişi adı yazmayın.', max_length=255, verbose_name='onay notu')),
                ('surplus_barcode', models.CharField(blank=True, default='', max_length=32, verbose_name='okutulan kod (sayım fazlası)')),
                ('surplus_note', models.CharField(blank=True, default='', help_text='Kitabın adı ve bulunduğu yer. Kişi adı yazmayın.', max_length=255, verbose_name='fazla açıklaması')),
                ('surplus_excluded', models.BooleanField(default=False, help_text='Kütüphaneye ait değil ya da kayıttan çıkmış (ör. imhayı bekleyen); gerekçe zorunlu.', verbose_name='kayda alınmayacak')),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stocktake_items', to='kutuphane.lossdamagecase', verbose_name='kayıp/hasar dosyası')),
                ('class_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='okul.classsection', verbose_name='sınıf kitaplığı (anlık görüntü)')),
                ('copy', models.ForeignKey(blank=True, help_text='Boş = sayım fazlası.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stocktake_items', to='kutuphane.copy', verbose_name='nüsha')),
                ('created_copy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='kutuphane.copy', verbose_name='onayda açılan nüsha')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='kutuphane.section', verbose_name='bölüm (anlık görüntü)')),
                ('stocktake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='kutuphane.stocktake', verbose_name='sayım')),
                ('surplus_copy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='kutuphane.copy', verbose_name='etiketin ait olduğu eski kayıt')),
                ('surplus_work', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='kutuphane.work', verbose_name='kayda alınacağı eser')),
            ],
            options={
                'verbose_name': 'sayım kalemi',
                'verbose_name_plural': 'sayım kalemleri',
                'ordering': ['stocktake', 'pk'],
            },
        ),
        migrations.AddIndex(
            model_name='stocktake',
            index=models.Index(fields=['status'], name='kutuphane_st_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='stocktake',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['DRAFT', 'IN_PROGRESS', 'COMPLETED', 'APPROVED', 'CANCELLED'])), name='ck_stocktake_status'),
        ),
        migrations.AddConstraint(
            model_name='stocktake',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('open_slot', True), ('status__in', ['DRAFT', 'IN_PROGRESS', 'COMPLETED'])), models.Q(models.Q(('status__in', ['DRAFT', 'IN_PROGRESS', 'COMPLETED']), _negated=True), ('open_slot__isnull', True)), _connector='OR'), name='ck_stocktake_open_slot'),
        ),
        migrations.AddConstraint(
            model_name='stocktake',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('open_slot', True)), fields=('open_slot',), name='uq_stocktake_single_open'),
        ),
        migrations.AddConstraint(
            model_name='stocktake',
            constraint=models.CheckConstraint(condition=models.Q(('loan_basis__in', ['COLLECT', 'BY_RECORD'])), name='ck_stocktake_loan_basis'),
        ),
        migrations.AddConstraint(
            model_name='stocktake',
            constraint=models.CheckConstraint(condition=models.Q(('section_delivery_basis__in', ['IN_PLACE', 'COLLECT'])), name='ck_stocktake_section_basis'),
        ),
        migrations.AddConstraint(
            model_name='stocktake',
            constraint=models.CheckConstraint(condition=models.Q(('teacher_delivery_basis__in', ['COLLECT', 'BY_RECORD'])), name='ck_stocktake_teacher_basis'),
        ),
        migrations.AddConstraint(
            model_name='stocktake',
            constraint=models.CheckConstraint(condition=models.Q(('repair_basis__in', ['COLLECT', 'BY_RECORD'])), name='ck_stocktake_repair_basis'),
        ),
        migrations.AddConstraint(
            model_name='stocktake',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('tmy_stop', False), ('tmy_stop_by_name', ''), ('tmy_stop_on__isnull', True), ('tmy_stop_requested_on__isnull', True)), models.Q(('status__in', ['DRAFT', 'CANCELLED']), ('tmy_stop', True)), models.Q(('tmy_stop', True), ('tmy_stop_on__isnull', False), ('tmy_stop_requested_on__isnull', False), models.Q(('tmy_stop_by_name', ''), _negated=True)), _connector='OR'), name='ck_stocktake_tmy_stop'),
        ),
        migrations.AddConstraint(
            model_name='stocktake',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('started_at__isnull', True), ('status', 'DRAFT')), models.Q(('fiscal_year__isnull', False), ('started_at__isnull', False), ('status__in', ['IN_PROGRESS', 'COMPLETED', 'APPROVED'])), ('status', 'CANCELLED'), _connector='OR'), name='ck_stocktake_started'),
        ),
        migrations.AddConstraint(
            model_name='stocktake',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('round', 1), ('round2_started_at__isnull', True)), models.Q(('round', 2), ('round2_started_at__isnull', False)), _connector='OR'), name='ck_stocktake_round'),
        ),
        migrations.AddConstraint(
            model_name='stocktake',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('completed_at__isnull', False), ('status__in', ['COMPLETED', 'APPROVED'])), models.Q(('completed_at__isnull', True), ('status__in', ['DRAFT', 'IN_PROGRESS'])), ('status', 'CANCELLED'), _connector='OR'), name='ck_stocktake_completed'),
        ),
        migrations.AddConstraint(
            model_name='stocktake',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('approved_at__isnull', False), ('approved_on__isnull', False), ('status', 'APPROVED'), models.Q(('approved_by_name', ''), _negated=True)), models.Q(models.Q(('status', 'APPROVED'), _negated=True), ('approved_at__isnull', True), ('approved_by_name', ''), ('approved_on__isnull', True), ('surplus_acquisition__isnull', True)), _connector='OR'), name='ck_stocktake_approval'),
        ),
        migrations.AddConstraint(
            model_name='stocktake',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('cancelled_at__isnull', False), ('status', 'CANCELLED')), models.Q(models.Q(('status', 'CANCELLED'), _negated=True), ('cancelled_at__isnull', True)), _connector='OR'), name='ck_stocktake_cancelled_at'),
        ),
        migrations.AddIndex(
            model_name='stocktakeitem',
            index=models.Index(fields=['stocktake', 'result'], name='kutuphane_sti_result_idx'),
        ),
        migrations.AddConstraint(
            model_name='stocktakeitem',
            constraint=models.UniqueConstraint(condition=models.Q(('copy__isnull', False), ('deleted_at__isnull', True)), fields=('stocktake', 'copy'), name='uq_stocktakeitem_copy'),
        ),
        migrations.AddConstraint(
            model_name='stocktakeitem',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('surplus_barcode', ''), _negated=True), ('deleted_at__isnull', True)), fields=('stocktake', 'surplus_barcode'), name='uq_stocktakeitem_surplus_barcode'),
        ),
        migrations.AddConstraint(
            model_name='stocktakeitem',
            constraint=models.CheckConstraint(condition=models.Q(('result__in', ['PENDING', 'FOUND', 'BY_RECORD', 'MISSING', 'SURPLUS', 'EXITED'])), name='ck_stocktakeitem_result'),
        ),
        migrations.AddConstraint(
            model_name='stocktakeitem',
            constraint=models.CheckConstraint(condition=models.Q(('outcome', ''), ('outcome__in', ['WRITTEN_OFF', 'NOT_APPROVED', 'STATE_CHANGED', 'RECONCILED', 'ENTERED', 'NOT_ENTERED']), _connector='OR'), name='ck_stocktakeitem_outcome'),
        ),
        migrations.AddConstraint(
            model_name='stocktakeitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('copy__isnull', False), ('created_copy__isnull', True), ('surplus_barcode', ''), ('surplus_copy__isnull', True), ('surplus_excluded', False), ('surplus_note', ''), ('surplus_work__isnull', True), models.Q(('expected_status', ''), _negated=True), models.Q(('basis', ''), _negated=True), models.Q(('result', 'SURPLUS'), _negated=True)), models.Q(('basis', ''), ('copy__isnull', True), ('damage_write_off', False), ('expected_status', ''), ('result', 'SURPLUS'), ('status_at_completion', '')), _connector='OR'), name='ck_stocktakeitem_kind'),
        ),
        migrations.AddConstraint(
            model_name='stocktakeitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('surplus_excluded', True), ('surplus_work__isnull', False), _negated=True), models.Q(models.Q(('surplus_excluded', True), _negated=True), models.Q(('surplus_note', ''), _negated=True), _connector='OR')), name='ck_stocktakeitem_surplus_choice'),
        ),
        migrations.AddConstraint(
            model_name='stocktakeitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('found_in_round__isnull', False), ('result', 'FOUND'), models.Q(('found_via', ''), _negated=True)), models.Q(models.Q(('result', 'FOUND'), _negated=True), ('found_in_round__isnull', True), ('found_via', '')), _connector='OR'), name='ck_stocktakeitem_found'),
        ),
        migrations.AddConstraint(
            model_name='stocktakeitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('outcome', 'WRITTEN_OFF'), models.Q(('write_off_path', ''), _negated=True)), models.Q(models.Q(('outcome', 'WRITTEN_OFF'), _negated=True), ('write_off_path', '')), _connector='OR'), name='ck_stocktakeitem_write_off_path'),
        ),
        migrations.AddConstraint(
            model_name='stocktakeitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('outcome', 'NOT_APPROVED'), _negated=True), models.Q(('outcome_note', ''), _negated=True), _connector='OR'), name='ck_stocktakeitem_not_approved_note'),
        ),
    ]
