# Generated by Django 5.1.15 on 2026-09-25 22:27
#
# F10 — tek göç (D kolu): sayıma "yıl sonu sayımı" işareti (F9 ekleri K6; TMY 32/1,
# 34/2-a, 34/3-a — işaretsiz sayımın eki "Ara sayım" başlığını alır, yönetim hesabı
# cetveli hazırlığı yalnız işaretli ve onaylanmış sayımdan basılır), Kütüphane
# Politikası'na "Bakanlık sistemi kullanımda" bayrağı (A21 — varsayılan KAPALI; yalnız
# ayrılış ve ilişik ekranlarında hatırlatma) ve çok okunanlar eşiğinin aralığı A12'ye
# göre 3-10 (önceki 2-50). Yeni alanların varsayılanı var olan satırlara yazılır
# (sayımlar işaretsiz, bayrak kapalı). Tek veri adımı: aralık dışında kalmış bir eşik
# en yakın sınıra çekilir — yoksa politikanın bir sonraki kaydı, kullanıcı eşiğe hiç
# dokunmasa da doğrulamada reddedilirdi.

import django.core.validators
from django.db import migrations, models


def _esigi_araliga_cek(apps, schema_editor):
    """Çok okunanlar eşiğini 3-10 aralığına çeker (geri göçte değere dokunulmaz)."""
    LibraryPolicy = apps.get_model("kutuphane", "LibraryPolicy")
    LibraryPolicy._base_manager.filter(popular_min_members__lt=3).update(popular_min_members=3)
    LibraryPolicy._base_manager.filter(popular_min_members__gt=10).update(popular_min_members=10)


class Migration(migrations.Migration):

    dependencies = [
        ('kutuphane', '0008_sayim'),
    ]

    operations = [
        migrations.AddField(
            model_name='librarypolicy',
            name='ministry_system_in_use',
            field=models.BooleanField(default=False, help_text='Okul, Bakanlık otomasyon sistemini de kullanıyorsa açılır. Açıkken ayrılış ve ilişik ekranları kaydın Bakanlık otomasyon sisteminde de güncellenmesini hatırlatır; program o sistemin yerine geçmez.', verbose_name='Bakanlık sistemi kullanımda'),
        ),
        migrations.AddField(
            model_name='stocktake',
            name='is_year_end',
            field=models.BooleanField(default=False, help_text='Yıl sonu sayımıysa işaretleyin (TMY 32/1). Taşınır Sayım ve Döküm Cetveline aktarılacak sayılar ve yönetim hesabı cetveli hazırlığı yalnız yıl sonu sayımından basılır.', verbose_name='yıl sonu sayımı'),
        ),
        migrations.AlterField(
            model_name='librarypolicy',
            name='popular_min_members',
            field=models.PositiveSmallIntegerField(default=5, help_text='Bir eser vitrine ancak en az bu kadar FARKLI üye ödünç aldıysa girer; sayı hiçbir yerde gösterilmez (profil yasağı, tasarım §3).', validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(10)], verbose_name='çok okunanlar için en az üye sayısı'),
        ),
        migrations.RunPython(_esigi_araliga_cek, migrations.RunPython.noop),
    ]
