# Generated by Django 5.1.15 on 2026-09-27 10:52

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kutuphane', '0009_yil_sonu_sayimi_ve_bakanlik_sistemi'),
        ('okul', '0006_kutuphane_saatleri'),
    ]

    operations = [
        migrations.CreateModel(
            name='BelgeIzi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tur', models.CharField(choices=[('E5', 'Kütüphaneden ilişiği yoktur belgesi'), ('E6', 'Kayıp/hasar tutanağı'), ('E15_TESLIM', 'Teslim listesi'), ('E15_GERI_ALMA', 'Geri alma dökümü')], max_length=16, verbose_name='belge türü')),
                ('belge_tarihi', models.DateField(verbose_name='belgenin tarihi')),
                ('belge_sayisi', models.CharField(blank=True, default='', help_text='Belge no (E15) ya da dosya numarası; kişisel veri yazılmaz.', max_length=255, verbose_name='belgenin sayısı')),
                ('kapsam', models.CharField(blank=True, default='', help_text='Kişisiz kısa açıklama.', max_length=255, verbose_name='kapsam')),
                ('adet', models.PositiveIntegerField(default=0, verbose_name='satır ya da sayfa sayısı')),
                ('sha256', models.CharField(max_length=64, verbose_name="PDF'in SHA-256 özeti")),
                ('uretildi', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='üretildiği zaman')),
                ('anonim_kopya', models.BooleanField(default=False, verbose_name='anonimleştirilmiş kopya')),
            ],
            options={
                'verbose_name': 'belge izi',
                'verbose_name_plural': 'belge izleri',
                'ordering': ['-uretildi', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='RetentionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ran_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='tetik zamanı')),
                ('backup_name', models.CharField(max_length=255, verbose_name='tetik öncesi yedek')),
                ('summary', models.JSONField(blank=True, default=dict, verbose_name='özet')),
                ('pre_migrate_removed', models.PositiveIntegerField(default=0, verbose_name='silinen güncelleme öncesi yedek')),
                ('pre_migrate_pending', models.JSONField(blank=True, default=list, verbose_name='silinemeyen güncelleme öncesi yedekler')),
                ('old_db_removed', models.PositiveIntegerField(default=0, verbose_name='silinen önceki veritabanı')),
                ('old_db_pending', models.JSONField(blank=True, default=list, verbose_name='silinemeyen önceki veritabanı dosyaları')),
            ],
            options={
                'verbose_name': 'saklama tetiği',
                'verbose_name_plural': 'saklama tetikleri',
                'ordering': ['-ran_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='RetentionState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pending_since', models.DateField(blank=True, null=True, verbose_name='onay bekleme başlangıcı')),
                ('last_scan_on', models.DateField(blank=True, null=True, verbose_name='son tarama günü')),
                ('last_scan', models.JSONField(blank=True, default=dict, verbose_name='son taramanın özeti')),
            ],
            options={
                'verbose_name': 'saklama taraması durumu',
                'verbose_name_plural': 'saklama taraması durumu',
            },
        ),
        migrations.RemoveConstraint(
            model_name='loan',
            name='ck_loan_cardless_reason',
        ),
        migrations.AddField(
            model_name='delivery',
            name='anonymized_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='anonimleştirilme zamanı'),
        ),
        migrations.AddField(
            model_name='librarypolicy',
            name='retention_years_left_person',
            field=models.PositiveSmallIntegerField(default=2, help_text='Ayrılıştan bu süre sonra kayıt silme adayı olur; silme yönetici onayıyladır (§6.4).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='okuldan ayrılan kişinin kaydında saklama (yıl)'),
        ),
        migrations.AddField(
            model_name='loan',
            name='anonymized_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='anonimleştirilme zamanı'),
        ),
        migrations.AddField(
            model_name='lossdamagecase',
            name='anonymized_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='anonimleştirilme zamanı'),
        ),
        migrations.AddConstraint(
            model_name='delivery',
            constraint=models.CheckConstraint(condition=models.Q(('anonymized_at__isnull', True), models.Q(models.Q(('status', 'OPEN'), _negated=True), ('personnel__isnull', True)), _connector='OR'), name='ck_delivery_anonymized'),
        ),
        migrations.AddConstraint(
            model_name='loan',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('cardless', False), ('cardless_reason', '')), models.Q(('cardless', True), models.Q(models.Q(('cardless_reason', ''), _negated=True), ('anonymized_at__isnull', False), _connector='OR')), _connector='OR'), name='ck_loan_cardless_reason'),
        ),
        migrations.AddConstraint(
            model_name='loan',
            constraint=models.CheckConstraint(condition=models.Q(('anonymized_at__isnull', True), models.Q(('cardless_reason', ''), ('membership__isnull', True), ('override_note', ''), ('override_reason', '')), _connector='OR'), name='ck_loan_anonymized'),
        ),
        migrations.AddConstraint(
            model_name='lossdamagecase',
            constraint=models.CheckConstraint(condition=models.Q(('anonymized_at__isnull', True), models.Q(models.Q(('resolution__in', ('PENDING', 'PRICE_DETERMINED', 'PRICE_RECEIVED')), _negated=True), ('membership__isnull', True), ('responsible_note', '')), _connector='OR'), name='ck_lossdamagecase_anonymized'),
        ),
        migrations.AddIndex(
            model_name='belgeizi',
            index=models.Index(fields=['tur', 'belge_tarihi'], name='kutuphane_belgeizi_tur_idx'),
        ),
        migrations.AddConstraint(
            model_name='belgeizi',
            constraint=models.CheckConstraint(condition=models.Q(('tur__in', ['E5', 'E6', 'E15_TESLIM', 'E15_GERI_ALMA'])), name='ck_belgeizi_tur'),
        ),
        migrations.AddConstraint(
            model_name='belgeizi',
            constraint=models.CheckConstraint(condition=models.Q(('sha256', ''), _negated=True), name='ck_belgeizi_sha256'),
        ),
        migrations.AddConstraint(
            model_name='retentionrun',
            constraint=models.CheckConstraint(condition=models.Q(('backup_name', ''), _negated=True), name='ck_retentionrun_backup'),
        ),
    ]
