"""TB11 — waitress'in kendi hata yanıtları Türkçe ve CSP'li (gerçek waitress ile).

İstek uygulamaya hiç ulaşmadan reddedildiğinde (bozuk istek satırı, büyük
başlık, büyük gövde) yanıtı waitress üretir. `katalog.waitress_hatalari.uygula`
sunucu örneğinin kanal sınıfını değiştirir; burada gerçek bir waitress
sunucusu loopback'te kurulur ve ham soketle kötü istekler gönderilir.
"""

from __future__ import annotations

import socket
import threading
from collections.abc import Iterator
from typing import Any

import pytest
from waitress.channel import HTTPChannel  # type: ignore[import-untyped]
from waitress.server import create_server  # type: ignore[import-untyped]

from katalog import app as katalog_app
from katalog import waitress_hatalari
from katalog.app import SIGNATURE_META, create_app
from katalog.bakim import BakimKapisi
from katalog.hatalar import CSP
from katalog.tests.conftest import genis_hiz_siniri

#: Katalog sunucusunun ayarları (desktop/katalog_server.py ile aynı sınırlar). Başlık
#: sınırı burada 1024'tür (gerçekte 8192): büyük başlıklı istek waitress'in TEK
#: okumasına sığsın ve sunucu okunmamış veriyle bağlantıyı kapatıp (RST) yanıtı
#: istemciye ulaşmadan silmesin. Sınanan yol aynıdır.
AYARLAR: dict[str, Any] = {
    "threads": 2,
    "max_request_body_size": 1024,
    "max_request_header_size": 1024,
    "ident": None,
    "expose_tracebacks": False,
    "clear_untrusted_proxy_headers": True,
}


@pytest.fixture
def sunucu() -> Iterator[tuple[str, int]]:
    uygulama = create_app(None, bakim_kapisi=BakimKapisi(), hiz_siniri=genis_hiz_siniri())
    sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    sock.bind(("127.0.0.1", 0))
    sock.listen(16)
    srv = create_server(uygulama, sockets=[sock], **AYARLAR)
    assert waitress_hatalari.uygula(srv) == 1
    is_parcacigi = threading.Thread(target=srv.run, daemon=True)
    is_parcacigi.start()
    try:
        yield sock.getsockname()
    finally:
        srv.close()
        srv.task_dispatcher.shutdown(cancel_pending=True, timeout=2)
        is_parcacigi.join(2)


def _ham_istek(adres: tuple[str, int], veri: bytes) -> tuple[str, dict[str, str], str]:
    with socket.create_connection(adres, timeout=5) as baglanti:
        baglanti.sendall(veri)
        parcalar: list[bytes] = []
        while True:
            parca = baglanti.recv(65536)
            if not parca:
                break
            parcalar.append(parca)
    ham = b"".join(parcalar).decode("utf-8", errors="replace")
    bas, _, govde = ham.partition("\r\n\r\n")
    satirlar = bas.split("\r\n")
    basliklar = {}
    for satir in satirlar[1:]:
        ad, _, deger = satir.partition(":")
        basliklar[ad.strip().lower()] = deger.strip()
    return satirlar[0], basliklar, govde


@pytest.mark.parametrize(
    ("istek", "kod", "baslik"),
    [
        (b"BOZUK ISTEK SATIRI\r\n\r\n", "400", "Geçersiz istek"),
        (
            b"GET / HTTP/1.1\r\nHost: x\r\nX-Uzun: " + b"a" * 2000 + b"\r\n\r\n",
            "431",
            "İstek çok büyük",
        ),
        (
            b"POST / HTTP/1.1\r\nHost: x\r\nContent-Length: 5000\r\n\r\n",
            "413",
            "İstek çok büyük",
        ),
    ],
    ids=["bozuk-istek-satiri", "buyuk-baslik", "buyuk-govde"],
)
def test_waitress_hata_yanitlari_turkce_ve_csp_li(
    sunucu: tuple[str, int], istek: bytes, kod: str, baslik: str
) -> None:
    durum, basliklar, govde = _ham_istek(sunucu, istek)

    assert durum.split(" ")[1] == kod, durum
    assert baslik in govde
    assert SIGNATURE_META in govde
    assert "generated by" not in govde
    assert basliklar["content-type"] == "text/html; charset=utf-8"
    assert basliklar["content-security-policy"] == CSP
    assert basliklar["x-content-type-options"] == "nosniff"
    assert basliklar["cache-control"] == "no-store"
    assert "server" not in basliklar


def test_uygulamaya_ulasan_istek_etkilenmez(sunucu: tuple[str, int]) -> None:
    durum, basliklar, govde = _ham_istek(
        sunucu, b"GET /saglik HTTP/1.1\r\nHost: x\r\nConnection: close\r\n\r\n"
    )

    assert durum.endswith("200 OK")
    assert govde == "tamam"


def test_kanal_sinifi_fikirdes_ve_mevcut_alt_sinifin_ustune_biner() -> None:
    class BaglantiSinirliKanal(HTTPChannel):  # type: ignore[misc]
        ozel = True

    birinci = waitress_hatalari.kanal_sinifi(BaglantiSinirliKanal)
    ikinci = waitress_hatalari.kanal_sinifi(birinci)

    assert ikinci is birinci
    assert issubclass(birinci, BaglantiSinirliKanal)
    assert birinci.error_task_class is waitress_hatalari.hata_gorevi_sinifi()
    assert katalog_app.WAITRESS_HATA_GOREVI is waitress_hatalari.hata_gorevi_sinifi()


def test_bilinmeyen_kod_500_sayfasina_duser() -> None:
    durum, basliklar, govde = waitress_hatalari.hata_yaniti(599)

    assert durum == "500 Internal Server Error"
    assert ("Content-Security-Policy", CSP) in basliklar
    assert "Bir sorun oluştu".encode() in govde


def test_cok_soketli_sunucuda_her_dinleyiciye_uygulanir() -> None:
    socketler = []
    for _ in range(2):
        s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        s.bind(("127.0.0.1", 0))
        s.listen(4)
        socketler.append(s)
    srv = create_server(create_app(None), sockets=socketler, **AYARLAR)
    try:
        assert waitress_hatalari.uygula(srv) == 2
    finally:
        srv.close()
        srv.task_dispatcher.shutdown(cancel_pending=True, timeout=2)
        for s in socketler:
            s.close()
