# Generated by Django 5.1.15 on 2026-08-29 14:49

import django.db.models.deletion
import django.utils.timezone
import shared.crypto
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='silinme')),
                ('first_name', shared.crypto.EncryptedCharField(max_length=100, verbose_name='ad')),
                ('last_name', shared.crypto.EncryptedCharField(max_length=100, verbose_name='soyad')),
                ('title', models.CharField(blank=True, default='', max_length=64, verbose_name='unvan')),
                ('branch', models.CharField(blank=True, default='', max_length=64, verbose_name='branş')),
                ('is_active', models.BooleanField(default=True, verbose_name='aktif')),
            ],
            options={
                'verbose_name': 'personel',
                'verbose_name_plural': 'personel',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='SchoolConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='silinme')),
                ('school_name', models.CharField(blank=True, default='', max_length=255, verbose_name='okul adı')),
                ('province', models.CharField(blank=True, default='', max_length=64, verbose_name='il')),
                ('district', models.CharField(blank=True, default='', max_length=64, verbose_name='ilçe')),
                ('principal_name', models.CharField(blank=True, default='', max_length=128, verbose_name='müdür adı')),
                ('school_type', models.CharField(choices=[('ANADOLU_LISESI', 'Anadolu Lisesi')], default='ANADOLU_LISESI', max_length=32, verbose_name='okul türü')),
                ('has_prep_class', models.BooleanField(default=False, verbose_name='hazırlık sınıfı var')),
                ('setup_completed', models.BooleanField(default=False, verbose_name='kurulum tamamlandı')),
                ('app_password_hash', models.CharField(blank=True, default='', max_length=255, verbose_name='uygulama parolası özeti')),
            ],
            options={
                'verbose_name': 'kurum yapılandırması',
                'verbose_name_plural': 'kurum yapılandırması',
            },
        ),
        migrations.CreateModel(
            name='ImportRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='silinme')),
                ('source_type', models.CharField(choices=[('STUDENTS', 'Öğrenci'), ('PERSONNEL', 'Personel')], db_index=True, max_length=16, verbose_name='kaynak türü')),
                ('file_name', models.CharField(blank=True, default='', max_length=255, verbose_name='dosya adı')),
                ('file_hash', models.CharField(db_index=True, max_length=64, verbose_name='içerik özeti (SHA256)')),
                ('status', models.CharField(choices=[('RUNNING', 'Çalışıyor'), ('COMPLETED', 'Tamamlandı'), ('FAILED', 'Başarısız'), ('PREVIEWED', 'Önizlendi')], default='RUNNING', max_length=16, verbose_name='durum')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='başlangıç')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='bitiş')),
                ('report', models.JSONField(blank=True, default=dict, verbose_name='rapor')),
            ],
            options={
                'verbose_name': 'içe aktarma koşusu',
                'verbose_name_plural': 'içe aktarma koşuları',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['source_type', 'file_hash'], name='okul_importrun_hash_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('status', 'COMPLETED')), fields=('source_type', 'file_hash'), name='uq_importrun_completed_per_hash')],
            },
        ),
        migrations.CreateModel(
            name='SchoolYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='silinme')),
                ('name', models.CharField(max_length=32, verbose_name='ad')),
                ('start_date', models.DateField(verbose_name='başlangıç')),
                ('end_date', models.DateField(verbose_name='bitiş')),
                ('is_active', models.BooleanField(default=False, verbose_name='aktif')),
            ],
            options={
                'verbose_name': 'ders yılı',
                'verbose_name_plural': 'ders yılları',
                'ordering': ['-start_date'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('name',), name='uq_schoolyear_name_alive'), models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('is_active', True)), fields=('is_active',), name='uq_schoolyear_single_active')],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='silinme')),
                ('first_name', shared.crypto.EncryptedCharField(max_length=100, verbose_name='ad')),
                ('last_name', shared.crypto.EncryptedCharField(max_length=100, verbose_name='soyad')),
                ('student_number', models.CharField(blank=True, default='', max_length=16, verbose_name='okul no')),
                ('class_level', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='sınıf')),
                ('class_section', models.CharField(blank=True, default='', max_length=8, verbose_name='şube')),
                ('status', models.CharField(choices=[('ACTIVE', 'Aktif'), ('LEFT', 'Ayrıldı')], default='ACTIVE', max_length=16, verbose_name='durum')),
            ],
            options={
                'verbose_name': 'öğrenci',
                'verbose_name_plural': 'öğrenciler',
                'ordering': ['class_level', 'class_section', 'student_number'],
                'indexes': [models.Index(fields=['class_level', 'class_section'], name='okul_student_class_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('status', 'ACTIVE'), models.Q(('student_number', ''), _negated=True)), fields=('student_number',), name='uq_student_number_active_alive')],
            },
        ),
        migrations.CreateModel(
            name='SchoolTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='silinme')),
                ('sequence', models.PositiveSmallIntegerField(choices=[(1, '1. dönem'), (2, '2. dönem')], verbose_name='dönem')),
                ('start_date', models.DateField(verbose_name='başlangıç')),
                ('end_date', models.DateField(verbose_name='bitiş')),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='okul.schoolyear', verbose_name='ders yılı')),
            ],
            options={
                'verbose_name': 'ders dönemi',
                'verbose_name_plural': 'ders dönemleri',
                'ordering': ['school_year', 'sequence'],
                'indexes': [models.Index(fields=['school_year', 'start_date'], name='schoolterm_year_start_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('school_year', 'sequence'), name='uq_schoolterm_year_sequence_alive'), models.CheckConstraint(condition=models.Q(('sequence__in', (1, 2))), name='ck_schoolterm_sequence'), models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='ck_schoolterm_date_order')],
            },
        ),
        migrations.CreateModel(
            name='ClassSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='silinme')),
                ('class_level', models.PositiveSmallIntegerField(verbose_name='sınıf')),
                ('class_section', models.CharField(max_length=8, verbose_name='şube')),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='class_sections', to='okul.schoolyear', verbose_name='ders yılı')),
            ],
            options={
                'verbose_name': 'şube',
                'verbose_name_plural': 'şubeler',
                'ordering': ['school_year', 'class_level', 'class_section'],
                'indexes': [models.Index(fields=['school_year', 'class_level', 'class_section'], name='okul_class_section_lookup_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('school_year', 'class_level', 'class_section'), name='uq_class_section_alive')],
            },
        ),
    ]
