# Generated by Django 5.1.15 on 2026-08-29 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okul', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolconfig',
            name='bell_schedule',
            field=models.JSONField(blank=True, default=list, help_text='[{"no": 1, "name": "1. Ders", "start": "08:30"}, ...] — boşsa varsayılan.', verbose_name='ders saati listesi'),
        ),
    ]
