# Generated by Django 5.1.15 on 2026-09-21 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okul', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='silinme')),
                ('name', models.CharField(max_length=128, verbose_name='ad')),
                ('start_date', models.DateField(db_index=True, verbose_name='başlangıç')),
                ('end_date', models.DateField(verbose_name='bitiş')),
                ('kind', models.CharField(choices=[('OFFICIAL', 'Resmî tatil'), ('RELIGIOUS', 'Dini bayram'), ('SCHOOL_BREAK', 'Öğrenciye kapalı gün'), ('OTHER', 'İdari izin / diğer')], default='OFFICIAL', max_length=16, verbose_name='tür')),
                ('is_estimated', models.BooleanField(default=False, verbose_name='tahmini')),
            ],
            options={
                'verbose_name': 'kapalı gün',
                'verbose_name_plural': 'kapalı günler',
                'ordering': ['start_date', 'end_date', 'pk'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('name', 'start_date'), name='uq_holiday_name_start_alive'), models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='ck_holiday_date_order'), models.CheckConstraint(condition=models.Q(('kind__in', ['OFFICIAL', 'RELIGIOUS', 'SCHOOL_BREAK', 'OTHER'])), name='ck_holiday_kind'), models.CheckConstraint(condition=models.Q(('is_estimated', False), ('kind', 'RELIGIOUS'), _connector='OR'), name='ck_holiday_estimated_religious')],
            },
        ),
    ]
