# Generated by Django 5.1.15 on 2026-08-30 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okul', '0002_schoolconfig_bell_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='silinme')),
                ('name', models.CharField(max_length=80, verbose_name='zümre adı')),
                ('is_board_member', models.BooleanField(default=True, help_text='Okul zümre başkanları kuruluna katılan zümre.', verbose_name='kurul üyesi')),
                ('head', models.ForeignKey(blank=True, help_text='Personel sicilinden seçilir; boş bırakılırsa evrakta noktalı çizgi basılır.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='chaired_departments', to='okul.personnel', verbose_name='zümre başkanı')),
            ],
            options={
                'verbose_name': 'zümre',
                'verbose_name_plural': 'zümreler',
                'ordering': ['pk'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('name',), name='uq_subjectdepartment_name_alive')],
            },
        ),
    ]
