# Generated by Django 5.1.15 on 2026-09-21 22:59
#
# F1-C (tasarım §6.1, §6.3): okul no şifreli + kör indeks, teklik kör indekse,
# `left_at`, `member_kind`; personelin unvan ve branş sütunları düşer (V2-01).
#
# VERİ GÖÇÜ YOKTUR, bilinçli: kör indeks veri anahtarından (DEK) türer ve
# anahtar `migrate` anında bellekte değildir. Yönetici parolası zorunlu olduğu
# ve `enable()` yalnız kişi tabloları boşken çalıştığı için bu göçü görecek
# yayımlanmış bir veritabanında düz okul no'lu satır bulunmaz. Olsaydı
# `manage.py app_password resume --force` (şifreleme geçişi:
# `app_password._rewrite_rows` → `Student.save`) numarayı şifreler ve indeksi
# doldururdu.

import shared.crypto
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okul', '0002_holiday'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['class_level', 'class_section', 'pk'], 'verbose_name': 'öğrenci', 'verbose_name_plural': 'öğrenciler'},
        ),
        migrations.RemoveConstraint(
            model_name='student',
            name='uq_student_number_active_alive',
        ),
        migrations.RemoveField(
            model_name='personnel',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='personnel',
            name='title',
        ),
        migrations.AddField(
            model_name='personnel',
            name='left_at',
            field=models.DateField(blank=True, null=True, verbose_name='ayrılış tarihi'),
        ),
        migrations.AddField(
            model_name='personnel',
            name='member_kind',
            field=models.CharField(choices=[('TEACHER', 'öğretmen'), ('STAFF', 'diğer personel')], default='TEACHER', max_length=16, verbose_name='üye türü'),
        ),
        migrations.AddField(
            model_name='student',
            name='left_at',
            field=models.DateField(blank=True, null=True, verbose_name='ayrılış tarihi'),
        ),
        migrations.AddField(
            model_name='student',
            name='student_number_index',
            field=models.CharField(blank=True, default='', editable=False, max_length=64, verbose_name='okul no kör indeksi'),
        ),
        migrations.AlterField(
            model_name='schoolconfig',
            name='app_password_hash',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='yönetici parolası parmak izi'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_number',
            field=shared.crypto.EncryptedCharField(blank=True, default='', max_length=16, verbose_name='okul no'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['student_number_index'], name='okul_student_numidx_idx'),
        ),
        migrations.AddConstraint(
            model_name='personnel',
            constraint=models.CheckConstraint(condition=models.Q(('member_kind__in', ['TEACHER', 'STAFF'])), name='ck_personnel_member_kind'),
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('status', 'ACTIVE'), models.Q(('student_number_index', ''), _negated=True)), fields=('student_number_index',), name='uq_student_number_index_active_alive'),
        ),
    ]
