# Generated by Django 5.1.15 on 2026-08-31 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okul', '0003_subjectdepartment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassSectionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='silinme')),
                ('name', models.CharField(max_length=60, verbose_name='küme adı')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='sıra')),
            ],
            options={
                'verbose_name': 'şube kümesi',
                'verbose_name_plural': 'şube kümeleri',
                'ordering': ['order', 'pk'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('name',), name='uq_classsectiongroup_name_alive')],
            },
        ),
        migrations.AddField(
            model_name='classsection',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Yalnız seçim kolaylığı; oturum kaydına küme kimliği YAZILMAZ.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sections', to='okul.classsectiongroup', verbose_name='şube kümesi'),
        ),
    ]
