# Generated by Django 5.1.15 on 2026-09-22 05:02
#
# F1-E (tasarım §3, §6.1, §14.1): kurulum sihirbazının okul adımı alanları —
# kademe, kısa okul adı, "bu bilgisayar okul demirbaşıdır" onayı ve
# bilgisayarın demirbaş no'su — ile Genel Bakış'taki "Başlangıç Yol Haritası"
# kartının kullanıcı işaretleri (`yol_haritasi`). Hiçbiri kişisel veri değildir.
# Veri göçü yoktur: var olan satır boş değerlerle gelir, sihirbaz eksik adımı
# gösterir.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okul', '0003_okul_no_kor_indeks_ayrilis_uye_turu'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolconfig',
            name='demirbas_no',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name="bilgisayarın demirbaş no'su"),
        ),
        migrations.AddField(
            model_name='schoolconfig',
            name='demirbas_onayi',
            field=models.BooleanField(default=False, verbose_name='bilgisayar okul demirbaşıdır'),
        ),
        migrations.AddField(
            model_name='schoolconfig',
            name='kademe',
            field=models.CharField(blank=True, choices=[('ILKOKUL', 'İlkokul'), ('ORTAOKUL', 'Ortaokul'), ('ORTAOGRETIM', 'Ortaöğretim (lise)')], default='', max_length=16, verbose_name='kademe'),
        ),
        migrations.AddField(
            model_name='schoolconfig',
            name='kisa_ad',
            field=models.CharField(blank=True, default='', max_length=24, verbose_name='kısa okul adı'),
        ),
        migrations.AddField(
            model_name='schoolconfig',
            name='yol_haritasi',
            field=models.JSONField(blank=True, default=dict, verbose_name='başlangıç yol haritası işaretleri'),
        ),
        migrations.AddConstraint(
            model_name='schoolconfig',
            constraint=models.CheckConstraint(condition=models.Q(('kademe__in', ['ILKOKUL', 'ORTAOKUL', 'ORTAOGRETIM', ''])), name='ck_schoolconfig_kademe'),
        ),
    ]
