# Generated by Django 5.1.15 on 2026-09-22 17:47
#
# F1 eki 7 (kullanıcı kararı 22.09.2026) — AYRILIŞ HAVUZU: e-Okul aktarımı
# kimseyi ayırmaz ve silmez; listede bulunmayan aktif öğrenci ve personel
# `leave_candidate_since` (havuza giriş tarihi) + `leave_candidate_run` (hangi
# aktarımla; aktarım kaydı silinirse boşalır) ile havuza girer, durumu aktif
# kalır. Kısıt: havuzdaki kişi aktiftir (ayrılış havuz alanlarını temizler).
# Veri göçü yoktur: var olan kayıtlar havuzda değildir.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okul', '0004_kurulum_kademe_kisa_ad_demirbas_yol_haritasi'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='leave_candidate_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='okul.importrun', verbose_name='havuza ekleyen aktarım'),
        ),
        migrations.AddField(
            model_name='personnel',
            name='leave_candidate_since',
            field=models.DateField(blank=True, null=True, verbose_name='ayrılış havuzuna giriş tarihi'),
        ),
        migrations.AddField(
            model_name='student',
            name='leave_candidate_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='okul.importrun', verbose_name='havuza ekleyen aktarım'),
        ),
        migrations.AddField(
            model_name='student',
            name='leave_candidate_since',
            field=models.DateField(blank=True, null=True, verbose_name='ayrılış havuzuna giriş tarihi'),
        ),
        migrations.AddConstraint(
            model_name='personnel',
            constraint=models.CheckConstraint(condition=models.Q(('leave_candidate_since__isnull', True), ('is_active', True), _connector='OR'), name='ck_personnel_leave_candidate_active'),
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.CheckConstraint(condition=models.Q(('leave_candidate_since__isnull', True), ('status', 'ACTIVE'), _connector='OR'), name='ck_student_leave_candidate_active'),
        ),
    ]
