# Generated by Django 5.1.15 on 2026-09-03 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okul', '0004_classsectiongroup_classsection_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolconfig',
            name='catalog_stamp',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='katalog damgası'),
        ),
        migrations.AddField(
            model_name='schoolconfig',
            name='level_programs',
            field=models.JSONField(blank=True, default=dict, help_text='{"9": ["fen-lisesi-2025"], "10": ["anadolu-lisesi-2025"]} — boşsa varsayılan.', verbose_name='seviye bazlı çizelge programları'),
        ),
        migrations.AlterField(
            model_name='schoolconfig',
            name='school_type',
            field=models.CharField(choices=[('ANADOLU_LISESI', 'Anadolu Lisesi'), ('FEN_LISESI', 'Fen Lisesi'), ('SOSYAL_BILIMLER_LISESI', 'Sosyal Bilimler Lisesi'), ('ANADOLU_IMAM_HATIP_LISESI', 'Anadolu İmam Hatip Lisesi'), ('MESLEKI_VE_TEKNIK_ANADOLU_LISESI', 'Mesleki ve Teknik Anadolu Lisesi'), ('COK_PROGRAMLI_ANADOLU_LISESI', 'Çok Programlı Anadolu Lisesi'), ('GUZEL_SANATLAR_LISESI', 'Güzel Sanatlar Lisesi'), ('SPOR_LISESI', 'Spor Lisesi')], default='ANADOLU_LISESI', max_length=32, verbose_name='okul türü'),
        ),
    ]
