# Generated by Django 5.1.15 on 2026-09-03 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okul', '0005_okul_turu_cizelgeleri'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolconfig',
            name='daily_period_count',
            field=models.PositiveSmallIntegerField(default=8, help_text='Bir okul gününde kaç ders saati var (genel liselerde 8).', verbose_name='günlük ders saati sayısı'),
        ),
        migrations.AddField(
            model_name='schoolconfig',
            name='exam_period_nos',
            field=models.JSONField(blank=True, default=list, help_text='[1, 2, 3] — sınav yapılabilecek ders saatleri; boşsa tümü.', verbose_name='sınav ders saatleri'),
        ),
    ]
