# Generated by Django 5.1.15 on 2026-09-24 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okul', '0005_ayrilis_havuzu'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolconfig',
            name='kutuphane_saatleri',
            field=models.TextField(blank=True, default='', max_length=500, verbose_name='kütüphane saatleri'),
        ),
    ]
