# Generated by Django 5.1.15 on 2026-09-19 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okul', '0007_aihl_b_grubu_program_anahtarlari'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importrun',
            name='source_type',
            field=models.CharField(choices=[('STUDENTS', 'Öğrenci'), ('PERSONNEL', 'Personel'), ('ELECTIVES', 'Seçmeli ders öğrencileri')], db_index=True, max_length=16, verbose_name='kaynak türü'),
        ),
    ]
