# Generated by Django 5.1.15 on 2026-09-19 16:44

import django.db.models.deletion
import shared.crypto
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okul', '0008_alter_importrun_source_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importrun',
            name='source_type',
            field=models.CharField(choices=[('STUDENTS', 'Öğrenci'), ('PERSONNEL', 'Personel'), ('ELECTIVES', 'Seçmeli ders öğrencileri'), ('PHOTOS', 'Öğrenci fotoğrafları')], db_index=True, max_length=16, verbose_name='kaynak türü'),
        ),
        migrations.CreateModel(
            name='StudentPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='silinme')),
                ('image', shared.crypto.EncryptedTextField(help_text='Yeniden kodlanmış JPEG (base64).', verbose_name='fotoğraf')),
                ('sha256', models.CharField(help_text="Yeniden kodlanmış JPEG'in özeti — aynı fotoğrafın yeniden aktarımını ayırt eder.", max_length=64, verbose_name='özet')),
                ('width', models.PositiveSmallIntegerField(verbose_name='genişlik')),
                ('height', models.PositiveSmallIntegerField(verbose_name='yükseklik')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='photo', to='okul.student', verbose_name='öğrenci')),
            ],
            options={
                'verbose_name': 'öğrenci fotoğrafı',
                'verbose_name_plural': 'öğrenci fotoğrafları',
                'ordering': ['student'],
            },
        ),
    ]
