# Generated by Django 5.1.15 on 2026-09-20 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okul', '0009_studentphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectdepartment',
            name='branches',
            field=models.JSONField(blank=True, default=list, help_text='Zümrenin öğretmen sicilindeki branşları; başkan adayları bunlardan listelenir.', verbose_name='branşlar'),
        ),
    ]
