# Generated by Django 5.1.15 on 2026-09-20 12:15

import shared.crypto
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('okul', '0010_subjectdepartment_branches'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='gender',
            field=shared.crypto.EncryptedCharField(blank=True, default='', max_length=1, verbose_name='cinsiyet'),
        ),
    ]
