# Generated by Django 5.1.15 on 2026-09-20 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okul', '0011_student_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolconfig',
            name='default_separation_mode',
            field=models.CharField(choices=[('NONE', 'Kapalı'), ('DESK', 'Aynı sıraya oturtma'), ('ROOM', 'Ayrı salonlar')], default='NONE', max_length=8, verbose_name='kız/erkek ayrışması varsayılanı'),
        ),
    ]
