# Generated by Django 5.1.15 on 2026-09-20 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okul', '0012_separation'),
    ]

    operations = [
        migrations.AddField(
            model_name='classsection',
            name='shift',
            field=models.CharField(blank=True, choices=[('MORNING', 'Sabah'), ('AFTERNOON', 'Öğleden sonra')], default='', help_text='İkili eğitimde şubenin oturumu; tam gün okulda boş bırakılır.', max_length=10, verbose_name='oturum'),
        ),
        migrations.AddField(
            model_name='schoolconfig',
            name='afternoon_bell_flow',
            field=models.JSONField(blank=True, default=dict, verbose_name='öğleden sonra ders akışı'),
        ),
        migrations.AddField(
            model_name='schoolconfig',
            name='afternoon_bell_schedule',
            field=models.JSONField(blank=True, default=list, help_text='İkili eğitimde öğle grubunun çizelgesi; boşsa sabahınki kullanılır.', verbose_name='öğleden sonra ders saatleri'),
        ),
        migrations.AddField(
            model_name='schoolconfig',
            name='bell_flow',
            field=models.JSONField(blank=True, default=dict, verbose_name='ders akışı'),
        ),
        migrations.AddField(
            model_name='schoolconfig',
            name='education_model',
            field=models.CharField(choices=[('FULL_DAY', 'Tam gün'), ('DUAL', 'İkili eğitim')], default='FULL_DAY', max_length=10, verbose_name='eğitim modeli'),
        ),
    ]
