"""waitress'in kendi hata yanıtları Türkçe ve CSP'li (teknik borç TB11, tasarım §5.4).

Bazı istekler uygulamaya HİÇ ULAŞMAZ: istek satırı bozuksa (400), başlıklar
`max_request_header_size`'ı aşıyorsa (431), gövde `max_request_body_size`'ı
aşıyorsa (413) ya da uygulama istisna fırlatırsa (500) yanıtı waitress kendisi
üretir. Özgün yanıt İngilizce düz metindir, gövdesinde "(generated by …)"
yazar ve CSP başlığı taşımaz; okul ağındaki tarayıcı Ağ Kataloğunun sabit
Türkçe sayfaları yerine bunu görürdü.

waitress'te bu yanıtları üreten tek yol `HTTPChannel.error_task_class`'tır
(`waitress.task.ErrorTask.execute` → `request.error.to_response()`). Burada o
sınıf alt sınıfla değiştirilir: gövde `katalog.hatalar`'daki aynı sabit
sayfadır, başlıklar uygulamanın güvenlik başlıklarıdır. Kanal sınıfı SUNUCU
ÖRNEĞİNDE değiştirilir (`uygula`): yönetim sunucusu (`kd-wsgi`) aynı süreçte
özgün waitress sınıflarıyla çalışmayı sürdürür, küresel yama yoktur.

`uygula`, sunucunun o an kullandığı kanal sınıfını TABAN alır: masaüstü kolu
kabul anındaki IP başına bağlantı sınırı için kendi kanal ya da sunucu alt
sınıfını kurmuşsa bu adım onu bozmadan üstüne biner. Fikirdeştir.

waitress bu modül içe aktarılınca DEĞİL, `uygula` çağrılınca yüklenir: katalog
uygulaması waitress'e bağımlı değildir, bu kanca yalnız masaüstü sunucusu
içindir.
"""

from __future__ import annotations

import functools
from typing import Any, Final

from katalog.hatalar import HATA_SAYFALARI, HTML, NO_STORE, SECURITY_HEADERS

#: Kanal sınıfının Türkçe hata görevini taşıdığını gösteren işaret (fikirdeşlik).
_ISARET: Final = "_kd_turkce_hata_gorevi"


def hata_yaniti(kod: int) -> tuple[str, list[tuple[str, str]], bytes]:
    """waitress hata kodu → (durum satırı, başlıklar, gövde); bilinmeyen kod 500 olur."""
    status, govde = HATA_SAYFALARI.get(kod, HATA_SAYFALARI[500])
    basliklar = [("Content-Type", HTML), *SECURITY_HEADERS, ("Cache-Control", NO_STORE)]
    return status, basliklar, govde


@functools.cache
def hata_gorevi_sinifi() -> type[Any]:
    """`waitress.task.ErrorTask`'ın Türkçe sayfa üreten alt sınıfı (bir kez kurulur).

    Masaüstü kolu bunu kendi kanal sınıfının `error_task_class`'ı yapabilir
    (`katalog.app.WAITRESS_HATA_GOREVI` aynı sınıftır) ya da `uygula` ile
    sunucu örneğine bağlayabilir.
    """
    from waitress.task import ErrorTask  # type: ignore[import-untyped]

    class KatalogHataGorevi(ErrorTask):  # type: ignore[misc]
        """`ErrorTask.execute`'un katalog karşılığı: aynı akış, Türkçe sabit sayfa."""

        def execute(self) -> None:
            hata = self.request.error
            status, basliklar, govde = hata_yaniti(int(getattr(hata, "code", 500)))
            self.status = status
            self.response_headers.extend(basliklar)
            self.set_close_on_finish()
            self.content_length = len(govde)
            self.write(govde)

    return KatalogHataGorevi


def kanal_sinifi(taban: type[Any]) -> type[Any]:
    """`taban` kanal sınıfının Türkçe hata görevli alt sınıfı (zaten öyleyse kendisi)."""
    if getattr(taban, _ISARET, False):
        return taban
    return type(
        "KatalogKanali",
        (taban,),
        {"error_task_class": hata_gorevi_sinifi(), _ISARET: True},
    )


def uygula(sunucu: Any) -> int:
    """`waitress.create_server`'ın döndürdüğü sunucuya uygular; değişen dinleyici sayısı.

    Tek soketli kurulumda dönen nesne dinleyicinin kendisidir; çok soketli
    kurulumda (`MultiSocketServer`) dinleyiciler sunucunun eşleminde durur.
    """
    if hasattr(sunucu, "channel_class"):
        dinleyiciler = [sunucu]
    else:
        dinleyiciler = [
            nesne
            for nesne in list(getattr(sunucu, "map", {}).values())
            if hasattr(nesne, "channel_class")
        ]
    for dinleyici in dinleyiciler:
        dinleyici.channel_class = kanal_sinifi(dinleyici.channel_class)
    return len(dinleyiciler)
